### ISSUE TITLE
[Python] typemap typecheck for const SWIGTYPE & and SWIGTYPE & should not allow None to work

### ISSUE THREAD

**Issue by tmaslach** [swig/swig#1202]
Let's start with the simple example - if you create a module out of the below interface file, I would expect the following output when running the following:

```
>>> import ref_traceback
>>> ref_traceback.test()
Passing in Foo should result in FOO: FOO
Passing in Bar should result in BAR: BAR
Passing in None should result in BAR: BAR
```

In actuality, the first two work, but we get a traceback for the third one:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\swig_bugs\ref_traceback\ref_traceback.py", line 135, in test
    print ("Passing in None should result in BAR:", test.get(None))
  File "D:\swig_bugs\ref_traceback\ref_traceback.py", line 116, in get
    def get(self, *args): return _ref_traceback.Test_get(self, *args)
ValueError: invalid null reference in method 'Test_get', argument 2 of type 'Foo const &'
```

A const & should not be able to accept a None value - it doesn't make sense.  It should reject that.  On the other hand, it makes sense for BAR.

This is a very simple example.  In my real example, I have a another object called a Variant which can accept all sorts of integral types, including NULL.  And I define typemaps for Variant, so I don't have to ever construct a Variant object in python.  For any non-integral value, the method is overloaded with different variations in C++ to take the actual object (like const Foo &).  This design was created by others, I'm just wrapping it and have no say in changing that design.   Regardless, I expect when I pass in None, it'll be handled by the variant (which is capable of doing so), but the const Foo & typecheck gets hit first. 

Here is the interface file for recreating the problem:
```
%module(directors="1") ref_traceback

%inline %{
class Foo {};
class Bar {};

class Test 
{
public:
  const char *get(const Foo& foo) { return "FOO"; }
  const char *get(const Bar* bar) { return "BAR"; }
};
%}


%pythoncode %{
def test():
  test = Test()
  
  foo = Foo()
  print ("Passing in Foo should result in FOO:", test.get(foo))
  
  bar = Bar()
  print ("Passing in Bar should result in BAR:", test.get(bar))
  
  print ("Passing in None should result in BAR:", test.get(None))
%}

```

A possible fix?   I'm not sure this is the right solution and it affects more than just python, but changing the typemap typecheck definitions for const SWIGTYPE & and SWIGTYPE & would fix the problem (in swigtypes.swg).  For example, this:

```
%typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1,implicitconv=1) const SWIGTYPE & {
  int res = SWIG_ConvertPtr($input, 0, $descriptor, %implicitconv_flag);
  $1 = SWIG_CheckState(res);
}
```

could be changed to:

```
%typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1,implicitconv=1) const SWIGTYPE & {
  void *vptr = 0;
  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, %implicitconv_flag);
  $1 = SWIG_CheckState(res) && vptr != 0;
}
```

I've confirmed this works.  But, it's a pretty wide sweeping change affecting all languages.  Also, part of me thinks SWIG_ConvertPtr should be handling this internally, but that would require passing more information into that method (can the value be NULL?)

**Comment by tmaslach** [comment]
Btw - I'm using SWIG 2.0.11, but I don't see this fixed in the latest swig-master branch...

**Comment by ojwb** [comment]
2.0.11 is ancient (approaching 5 years old) - do you mean 3.0.11?

It's undefined behaviour to make a reference from a NULL pointer so we really shouldn't be doing that, and I think this does need to be a sweeping change for all languages where this is currently possible.  It may break some cases where user wrappers currently seem to work OK, but they are actually invoking undefined behaviour and relying on nothing bad happening, which isn't a good situation.  And  SWIG 4.0.0 is a good time to make that sort of potentially incompatible change.

What effect does the change you suggest above have on the test suite?

**Comment by wsfulton** [comment]
This change makes sense to me and is how it ought to be implemented. It'll need applying consistently across all reference typecheck typemaps.

**Comment by tmaslach** [comment]
No, I really meant 2.0.11.  My company is finally joining the 3.X bandwagon in the next few months, fortunately.  

When I get myself a little free time, I'll go ahead and try this change and run it against the tests.  I'll just need to figure out how to do all that first!

**Comment by tmaslach** [comment]
I ran my change on [Travis](https://travis-ci.org/tmaslach/swig/builds/353663368).  

Looks like all languages are fine, except python has a couple of failures. I'll try to look at these in the evening, but I may have questions..

**Comment by tmaslach** [comment]
Here is an update - two failures. The first one I understand, I'll have to get back to the second one when I have time.

The first failure is due to my change, but I'm not sure how to fix it.  The code being wrapped is this:

```
struct A
{
	int ii;
	A(int i) { ii = 1; }
	A(double d) { ii = 2; }
	A(const B& b) { ii = 3; }
	explicit A(char *s) { ii = 4; }

	int get() const { return ii; }
};
```

The test is making sure this:

 ` A(None).get()`

raises a ValuError exception.  Before my change, it did because the 'const B& b'
typecheck would cause an immediate error out.

But with my fix, it quietly passes to the next typecheck, which is the char *s. 
That CAN accept a NULL pointer, so get() returns 4.  And that is a test failure, since it didn't raise a ValueError exception.

Any opinion on what should be done here?  My thought is that the test returning
4 is the correct answer, given we don't know if NULL is or isn't a valid option
for a char*.  If 4 isn't the right answer, that is up to the const char * typecheck to prevent. 

Do people agree with my assessment?  I'm not sure what the policy on changing tests are, but that is what I was going to recommend (i'd add a test as well elsewhere).

**Comment by ojwb** [comment]
If you'd just quoted a bit more context then the conclusion would be obvious - an existing comment in that testcase actually notes that your behaviour is what ought to happen:

```
try:
    check(3, A(None).get())
    raise RuntimeError
except ValueError:
    # ValueError: invalid null reference in method 'new_A', argument 1 of type 'B const &'
    # Arguably A(char *) should be chosen, but there is a bug to do with None passed to methods overloaded by value,
    # references and pointers to different types, where pointers ought to be
    # given a slightly higher precedence.
    pass
```

So that ought to be:

```
# Should choose A(char *) not A(const B&) as a NULL reference is invalid.
check(4, A(None).get())
```

**Comment by tmaslach** [comment]
Argh! I should've caught that...

OK, that change should be straight forward. I will look at the other test failure soon as well. Thanks!

**Comment by tmaslach** [comment]
Hi, so I changed the test around as recommended to get the implicittest_runme.py to run.  We're all set on that one.

I'm getting another failure in refcount_runme.py now.  The reason for this failure is that I modified the implicitconv typechecks as well (see my commit https://github.com/tmaslach/swig/commit/1a850a3948ccf6ac432b0a392c54e498af9402e1, line 373).

But, I believe I need to modify those.  Please correct me if I'm wrong.

The problem is that, by passing the vptr into SWIG_ConvertPtr with the SWIG_POINTER_IMPLICIT_CONV flag, we are incrementing the reference count somewhere (still tracking where, my linux debugging is rusty).  I've confirmed that if I don't pass &vptr in, but 0, the problem goes away. But, like I said, I'm not confident that is the right solution.

I tried changing the typecheck code to this:

```
%typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1,implicitconv=1) const SWIGTYPE & {
  void *vptr = 0;
  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, %implicitconv_flag);
  $1 = SWIG_CheckState(res) && vptr != 0;
  if (SWIG_IsNewObj(res)) {
    $ltype temp = 0;
    temp = %reinterpret_cast(vptr, $ltype);
    %delete (temp);
  }
}
```

This fixes the refcount_runme failure, which is good.  The fix may be slightly inefficient (creating and deleting an object right after.  But, the bigger concern is I get another test failure - class_scope_weird_wrap.cxx doesn't build.  Why?  Because, in this cxx file, we generate code using the above typecheck to delete a matrix4 object.  But, the matrix4 object is only forward declared.  That can't obvious be deleted, and the compiler knows it (complaining about an incomplete type).  This smells like a test problem personally, but I wanted to see what you guys thought.

**Comment by ojwb** [comment]
I think the forward declarations in `class_scope_weird_wrap.cxx` are OK.

(I am dubious SWIG ought to allow the extra qualifications that it's testing are allowed - we aim to support ISO C and C++, not invalid code that some compilers fail to error on.  There was perhaps some argument for this when such compilers were prevalent and people had such extra qualifications from cut-and-pasting code without enough care, but GCC at least was fixed ages ago and people will have had to fix their code to get it to compile.)

**Comment by ojwb** [comment]
I had a look through the code of `SWIG_Python_ConvertPtrAndOwn()` and I think that in the `implicitconv` case the `typecheck` typemap should probably just check if there is an implicit conversion available, not actually run the code for it and convert an object only to throw it away, then convert it again if the overloaded form needing it is actually called.  The conversion code could have side effects so it seems very undesirable to call it when we don't actually use the result or call it twice when we do.

Probably the typecheck typemap should be something like this part of `SWIG_Python_ConvertPtrAndOwn()`:

```
    if (implicit_conv) {
      SwigPyClientData *data = ty ? (SwigPyClientData *) ty->clientdata : 0;
      if (data && !data->implicitconv) {
        PyObject *klass = data->klass;
        if (klass) {
```

That's actually already checkable using `%implicitconv_flag && SWIG_Python_CheckImplicit(ty) && SWIG_Python_ExceptionType(ty) != PyExec_RuntimeError` but it'd be cleaner to add a new helper function that combines the second and third checks.

@wsfulton Does that sound sensible to you?

**Comment by wsfulton** [comment]
If I've understood this right, @ojwb's proposal is to simply check if a type has implicit conversion turned on, not whether or not the type to convert to is correct.  This would effectively be doing nothing more than checking that a constructor exists when implicitconv is turned on.  This will nearly always succeed and so will give false positives about convertibility.  The point about avoiding the conversion and the subsequent side effects in the typecheck typemaps is absolutely correct though.  With that in mind, I think the correct implementation would  be for `SWIG_Python_ConvertPtrAndOwn()` to call the constructor wrapper (the `SWIG_Python_CallFunctor()` call below)
```c++
        if (klass) {
          PyObject *impconv;
          data->implicitconv = 1; /* avoid recursion and call 'explicit' constructors*/
          impconv = SWIG_Python_CallFunctor(klass, obj);
```
but to do it in a way that forces the constructor wrapper to not actually call the constructor, but merely report back that it would or would not be possible to call the constructor with the given type.  For this to work, we'd need to change the generated constructor wrapper code and without actually implementing this, I'm not sure what corner case problems we'd come up against.  For now, I'm tempted not to solve this problem (it hasn't been reported as an issue), and instead focus on fixing the problem in this issue only.

I have a solution which conveniently leaves the implicitconv behaviour untouched.  It simply works by passing additional information to `SWIG_Python_ConvertPtrAndOwn()` to indicate not to accept Python `None`.  The `SWIG_POINTER_NO_NULL` flag has been added to convey this additional information and can be extended across all the languages that use the SWIG runtime.  It would be used in the typecheck typemaps for passing types by value or reference (so not `SWIGTYPE*`).  It could also be used in the in typemaps too for a faster fail, but I havn't implemented this.  Patch for Python is:
```patch
diff --git a/Lib/python/pyrun.swg b/Lib/python/pyrun.swg
index 7f05021..0759b8f 100644
--- a/Lib/python/pyrun.swg
+++ b/Lib/python/pyrun.swg
@@ -1018,7 +1018,7 @@ SWIG_Python_ConvertPtrAndOwn(PyObject *obj, void **ptr, swig_type_info *ty, int
   if (obj == Py_None && !implicit_conv) {
     if (ptr)
       *ptr = 0;
-    return SWIG_OK;
+    return (flags & SWIG_POINTER_NO_NULL) ? SWIG_NullReferenceError : SWIG_OK;
   }
 
   res = SWIG_ERROR;
diff --git a/Lib/swigrun.swg b/Lib/swigrun.swg
index 1ef6761..59118ec 100644
--- a/Lib/swigrun.swg
+++ b/Lib/swigrun.swg
@@ -43,6 +43,7 @@
 /* Flags for pointer conversions */
 #define SWIG_POINTER_DISOWN        0x1
 #define SWIG_CAST_NEW_MEMORY       0x2
+#define SWIG_POINTER_NO_NULL       0x4
 
 /* Flags for new pointer objects */
 #define SWIG_POINTER_OWN           0x1
diff --git a/Lib/typemaps/swigtype.swg b/Lib/typemaps/swigtype.swg
index 87fab7e..581de1a 100644
--- a/Lib/typemaps/swigtype.swg
+++ b/Lib/typemaps/swigtype.swg
@@ -358,46 +358,46 @@
 
 %typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1) SWIGTYPE & {
   void *vptr = 0;
-  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, 0);
+  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, SWIG_POINTER_NO_NULL);
   $1 = SWIG_CheckState(res);
 }
 
 %typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1) SWIGTYPE && {
   void *vptr = 0;
-  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, 0);
+  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, SWIG_POINTER_NO_NULL);
   $1 = SWIG_CheckState(res);
 }
 
 #if defined(__cplusplus) && defined(%implicitconv_flag)
 %typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1,implicitconv=1) const SWIGTYPE & {
-  int res = SWIG_ConvertPtr($input, 0, $descriptor, %implicitconv_flag);
+  int res = SWIG_ConvertPtr($input, 0, $descriptor, SWIG_POINTER_NO_NULL | %implicitconv_flag);
   $1 = SWIG_CheckState(res);
 }
 
 %typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1,implicitconv=1) const SWIGTYPE && {
-  int res = SWIG_ConvertPtr($input, 0, $descriptor, %implicitconv_flag);
+  int res = SWIG_ConvertPtr($input, 0, $descriptor, SWIG_POINTER_NO_NULL | %implicitconv_flag);
   $1 = SWIG_CheckState(res);
 }
 
 %typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1,implicitconv=1) SWIGTYPE {
-  int res = SWIG_ConvertPtr($input, 0, $&descriptor, %implicitconv_flag);
+  int res = SWIG_ConvertPtr($input, 0, $&descriptor, SWIG_POINTER_NO_NULL | %implicitconv_flag);
   $1 = SWIG_CheckState(res);
 }
 #else
 %typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1) const SWIGTYPE & {
   void *vptr = 0;
-  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, 0);
+  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, SWIG_POINTER_NO_NULL);
   $1 = SWIG_CheckState(res);
 }
 %typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1) const SWIGTYPE && {
   void *vptr = 0;
-  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, 0);
+  int res = SWIG_ConvertPtr($input, &vptr, $descriptor, SWIG_POINTER_NO_NULL);
   $1 = SWIG_CheckState(res);
 }
 
 %typemap(typecheck,precedence=SWIG_TYPECHECK_POINTER,noblock=1) SWIGTYPE {
   void *vptr = 0;
-  int res = SWIG_ConvertPtr($input, &vptr, $&descriptor, 0);
+  int res = SWIG_ConvertPtr($input, &vptr, $&descriptor, SWIG_POINTER_NO_NULL);
   $1 = SWIG_CheckState(res);
 }
 #endif
Any thoughts on this?

**Comment by ojwb** [comment]
Special handling for `None` does seem like a clear improvement over the current situation.
