### ISSUE TITLE
NotImplementedError when using std::map with enum as key

### ISSUE THREAD

**Issue by rwslord** [swig/swig#1226]
I have the following code in C++:

```cpp

namespace mscl
{

class ChannelMask
{
public:
    ChannelMask();  //default constructor
};

class WirelessTypes
{
public:
    enum DerivedChannelType
    {
        derived_rms = 0,
        derived_peakToPeak = 1,
    };

    typedef std::map<DerivedChannelType, ChannelMask> DerivedChannelMasks;
};

}
```

My swig .i file looks like this:

```
%include "stdint.i"
%include "std_string.i"
%include "std_vector.i"
%include "std_map.i"
%include "std_shared_ptr.i"

%module mscl
%{
#include "../WirelessTypes.h"
%}

%include "../WirelessTypes.h"

namespace std
{
    %template(DerivedChannelMasks) map<mscl::WirelessTypes::DerivedChannelType, mscl::ChannelMask>;
};
```

SWIG compiles this without errors. 

If I run the following Python code when it was compiled with SWIG 3.0.6, it works fine. However, if I run the same code when it was compiled with **SWIG 3.0.12**, it gives the error shown below:

```python
masks = mscl.DerivedChannelMasks()
masks[mscl.WirelessTypes.derived_rms] = mscl.ChannelMask()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mscl.py", line 7696, in __setitem__
    return _mscl.DerivedChannelMasks___setitem__(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'DerivedChannelMasks___setitem__'.
  Possible C/C++ prototypes are:
    std::map< mscl::WirelessTypes::DerivedChannelType,mscl::ChannelMask >::__setitem__(std::map< enum mscl::WirelessTypes::DerivedChannelType,mscl::ChannelMask >::key_type const &)
    std::map< mscl::WirelessTypes::DerivedChannelType,mscl::ChannelMask >::__setitem__(std::map< enum mscl::WirelessTypes::DerivedChannelType,mscl::ChannelMask >::key_type const &,std::map< enum mscl::WirelessTypes::DerivedChannelType,mscl::ChannelMask >::mapped_type const &)
```

My apologies for the long example. This is part of a large project, and I tried narrowing it down as much as possible.

Issue with **SWIG 3.0.12** when running the following command:
```swig -c++ -python -modern -outdir <PATH_TO_OUTDIR> -o "..\MSCL_Wrap.cpp" "..\MSCL_Interface.i"```

**Comment by rwslord** [comment]
do I have any errors in the way that I'm using SWIG, or does everything look like it should be working?

**Comment by ojwb** [comment]
> My apologies for the long example.

The length is OK, the bigger problem is it isn't self-contained.  Presumably "the following code in C++" is `..\WirelessTypes.h` but there's no implementation for `ChannelMask`'s constructor.

FWIW, if I fill in an empty implementation then I seem to get the same error with git master.

> do I have any errors in the way that I'm using SWIG, or does everything look like it should be working?

It looks plausible to me.

BTW, you can replace:

```
%{
#include "../WirelessTypes.h"
%}

%include "../WirelessTypes.h"
```

with the contents of that header wrapped in `%inline {` and `}`, which is especially handy for making small self-contained reproducers.

**Comment by ojwb** [comment]
Here's a smaller and self-contained test-case, assuming that `ChannelMask`'s constructor isn't interesting:

```
%module mscl

%include "std_map.i"

%inline %{

enum DerivedChannelType
{
    derived_rms = 0,
    derived_peakToPeak = 1,
};

%}

%template(DerivedChannelMasks) std::map<DerivedChannelType, int>;
```

To run:

```
swig -c++ -python -modern  mscl.i && g++ -o _mscl.so -shared -fPIC `python-config --cflags` mscl_wrap.cxx && PYTHONPATH=. python -c 'import mscl; masks = mscl.DerivedChannelMasks(); masks[mscl.derived_rms] = 1'
```

Using `git bisect` with that shows that this stopped working in 91aba9f719273778fe0196f9bc8659131c9e2cf8 - @wsfulton: any ideas?

**Comment by rwslord** [comment]
Thanks for looking into this @ojwb ! Any ides on this would be great.

**Comment by rwslord** [comment]
Is there any way to work around this? I had to revert to an old version of SWIG which seems to have other issues that have been fixed in newer versions. 

I'm guessing since there hasn't been any new releases for a couple years, and it looks like 4.0 is under development, that you might be pushing this off until that is released. Is there any ETA on 4.0?

**Comment by wsfulton** [comment]
I'll look at this after 4.0.0 is released (hopefully early 2019). If you debug using the older version of SWIG and the newer version you will probably find one of the traits classes that makes it work. A workaround would be to add in the appropriate traits class in the newer version using a carefully located %{ %} block.

**Comment by rwslord** [comment]
Any chance that this issue can be looked at now that 4.0.0 has been released? Thank you!

**Comment by wsfulton** [comment]
The std_map.i file change in 91aba9f is the cause. It is a good change as previously it would convert the pointer without checking if it succeeded. The problem here it highlights a bug in the type conversion because SWIG's type tables do not know that `std::map<DerivedChannelType, int>` and `std::map<enum DerivedChannelType, int>` are the same type.

This is likely to be a risky fix for swig-4.0.x, so I will have a go at a later date for swig-4.1. Meanwhile, there are some reasonable workarounds you can choose from:

1. Use enum in your %template declaration: 
`%template(DerivedChannelMasks) std::map<enum DerivedChannelType, int>;`. There is then no need have both equivalent types.
2. Add a dummy method that uses the map, for example: `void takeDerivedChannelMasks(std::map<DerivedChannelType, int> dcm) {}`. This seems to have the desired effect of adding in the equivalent types into the type tables.

Below is the type table entry to look for. It shows that both `enum DerivedChannelType` and `DerivedChanndelType` in the type info for the map:

```
static swig_type_info _swigt__p_std__mapT_DerivedChannelType_int_std__lessT_DerivedChannelType_t_std__allocatorT_std__pairT_DerivedChannelType_const_int_t_t_t = {"_p_std__mapT_DerivedChannelType_int_std__lessT_DerivedChannelType_t_std__allocatorT_std__pairT_DerivedChannelType_const_int_t_t_t", "std::map< DerivedChannelType,int,std::less< DerivedChannelType >,std::allocator< std::pair< DerivedChannelType const,int > > > *|std::map< enum DerivedChannelType,int,std::less< enum DerivedChannelType >,std::allocator< std::pair< enum DerivedChannelType const,int > > > *|std::map< enum DerivedChannelType,int > *|std::map< DerivedChannelType,int > *", 0, 0, (void*)0, 0};
```

Please try in your large project to see if one of these workarounds are okay.

**Comment by rwslord** [comment]
Thank you for looking at this, we really appreciate it!

I tried out your first workaround of adding enum to the template declaration, and that works perfectly! I successfully compiled it using SWIG 4.0.0, ran my same test, and it no longer throws a NotImplementedError.

While it would be great to have this fixed in a future version (or at least an error/warning at build time), this workaround will get us by perfectly fine, so this is no longer high priority for us. 

Thank you again!

**Comment by vadz** [comment]
I ran into the same issue and came to the same conclusion as [the above comment](https://github.com/swig/swig/issues/1226#issuecomment-517803490), but I don't quite understand why is it a problem for Python and Java (see #1571 and #1992), but not for C# where it still manages to work, somehow.

In any case, `template_class<enum E>` and `template_class<E>` really should be recognized as being the same, i.e. their entries in the type table ought to be merged. I don't know if it's worth trying to fix it myself, @wsfulton will you merge a PR doing this or do you want to do it yourself?

**Comment by ojwb** [comment]
I recall seeing other issues where an extra or missing `enum` on a type name caused a problem - #2047 is the first I found.  It doesn't looks like the exact same issue as here, but it makes me wonder if we could just normalise away the `enum` on typenames.

Is there any situation in which we need to reference enum type Foo as `enum Foo` instead of `Foo` when generating C/C++ wrapper code?

**Comment by wsfulton** [comment]
To be honest, fixing this is likely to open a can of worms and I'd rather it didn't hold up the 4.1.0 release. There is a ton of other work still to be reviewed and worked on. Any patch would have to be really complete adding in lots of testcases and analysing differences using 'make partialcheck-test-suite' in order to understand regressions because any change in this area is likely to regress something else.

**Comment by wsfulton** [comment]
I can't see this being done for swig-4.1, so moving to swig-4.2 milestone.

**Comment by Hadsch** [comment]
In my case, I downgraded to swig-3.012: 

```
# Deinstall current version
apt-get remove swig

# Download the tar.gz from here: https://sourceforge.net/projects/swig/files/swig/swig-3.0.12/
tar -xf swig-3.0.12.tar.gz
cd swig-3.0.12
./configure
make
make install
```

**Comment by ojwb** [comment]
It's a shame to keep bumping this, but there is at least an easy workaround - just use `enum` in the `%template`, e.g. for my reproducer:

```
%template(DerivedChannelMasks) std::map<enum DerivedChannelType, int>;
```

**Comment by wsfulton** [comment]
Removed swig-4.4 milestone - This will have to be tackled with the other enum issues.
