### ISSUE TITLE
ModuleNotFoundError: No module named '_example' when trying to import in Python

### ISSUE THREAD

**Issue by gregersn** [swig/swig#1285]
example.c and example.i from the tutorial, here: http://www.swig.org/tutorial.html

I run 
`swig -python example.i`
```gcc -c example.c example_wrap.c `pkg-config python-3.6 --cflags` ```
``` gcc -shared example.o example_wrap.o -o _example.so `pkg-config python-3.6 --libs````

Then I start python, and try to do `import example`

I get the result:
```
>>> import example
Traceback (most recent call last):
  File "/d/home/greger/devel/tests/swig_test/example.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_example'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/d/home/greger/devel/tests/swig_test/example.py", line 17, in <module>
    _example = swig_import_helper()
  File "/d/home/greger/devel/tests/swig_test/example.py", line 16, in swig_import_helper
    return importlib.import_module('_example')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_example'

```

This is done on windows 10, with msys2/mingw64
Python 3.6.2
mingw64/mingw-w64-x86_64-swig 3.0.12-1 [installed]

**Comment by ivanstepanovftw** [comment]
same for me

**Comment by wsfulton** [comment]
The Windows version of Python requires extension dlls to have the `.pyd` suffix. If you change your last line to generate `_example.pyd` rather than `_example.so` I suspect it will work.

The tutorial link you gave points to the wiki https://github.com/swig/swig/wiki/FAQ#shared-libraries but doesn't mention this aspect for Mingw. Feel free to update the wiki and then this issue can be closed.

**Comment by wsfulton** [comment]
Wiki page updated
