### ISSUE TITLE
undefined symbol: Py_InitModule4_64

### ISSUE THREAD

**Issue by ThyrixYang** [swig/swig#1295]
I'm trying swig for python binding, but when I followed section 36.2 in this page: http://www.swig.org/Doc3.0/Python.html#Python

I have compiled and got the example.py file, but when I import it, error occurred:

Traceback (most recent call last):
  File "/home/thyrix/Downloads/mlss_ps8_(adaboost)/example.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/thyrix/Downloads/mlss_ps8_(adaboost)/_example.cpython-36m-x86_64-linux-gnu.so: undefined symbol: Py_InitModule4_64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thyrix/Downloads/mlss_ps8_(adaboost)/example.py", line 17, in <module>
    _example = swig_import_helper()
  File "/home/thyrix/Downloads/mlss_ps8_(adaboost)/example.py", line 16, in swig_import_helper
    return importlib.import_module('_example')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/thyrix/Downloads/mlss_ps8_(adaboost)/_example.cpython-36m-x86_64-linux-gnu.so: undefined symbol: Py_InitModule4_64

How to fix it? Or does this because the page is outdated?
OS: ubuntu 18.04, python3.6

**Comment by ThyrixYang** [comment]
Seems my own fault.
