### ISSUE TITLE
swig -python -doxygen segfaults at "@param ..."

### ISSUE THREAD

**Issue by dweindl** [swig/swig#1643]
Hi, I am trying to use the `-doxygen` option for generating PyDoc comments. I stumbled over PyDocConverter seemingly having trouble handling `@param ...` inside the documentation of variadic functions.

Minimal example (tested with SWIG 4.0.1):
`test.i`:
```
%module test

/**
 * @brief Test fun
 * @param ... extra args
 */
void test_fun(...);
```
`swig -doxygen -python -c++  test.i`
-> Program received signal SIGSEGV, Segmentation fault.

See stack trace:
```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff7e8b73c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00005555555a897a in std::operator==<char, std::char_traits<char>, std::allocator<char> > (__rhs="...", __lhs=<optimized out>) at /usr/include/c++/8/bits/basic_string.h:6108
#3  std::operator!=<char, std::char_traits<char>, std::allocator<char> > (__rhs="...", __lhs=<optimized out>) at /usr/include/c++/8/bits/basic_string.h:6110
#4  PyDocConverter::getParamType (this=<optimized out>, param="...") at Doxygen/pydoc.cxx:421
#5  0x00005555555aac8b in PyDocConverter::handleTagParam (this=0x555555721a50, tag=..., translatedComment="\nTest fun\n") at /usr/include/c++/8/bits/basic_string.h:936
#6  0x00005555555a8d07 in PyDocConverter::translateSubtree[abi:cxx11](DoxygenEntity&) (this=0x555555721a50, doxygenEntity=...) at /usr/include/c++/8/bits/stl_list.h:209
#7  0x00005555555ac4d6 in PyDocConverter::makeDocumentation (this=0x555555721a50, n=<optimized out>) at Doxygen/pydoc.cxx:889
#8  0x000055555559e9cd in DoxygenTranslator::getDocumentation (this=0x555555721a50, node=0x555555bc6570, indentationString=0x0) at Doxygen/doxytranslator.cxx:58
#9  0x000055555564e81c in PYTHON::build_combined_docstring (low_level=true, indent=0x5555556d9b0a, ad_type=<optimized out>, n=0x555555bc6570, this=<optimized out>) at Modules/python.cxx:1516
#10 PYTHON::cdocstring (low_level=true, ad_type=<optimized out>, n=0x555555bc6570, this=<optimized out>) at Modules/python.cxx:1596
#11 PYTHON::add_method (this=0x555555720c30, name=<optimized out>, function=0x555555e50930, kw=0, n=0x555555bc6570, funpack=0, num_required=0, num_arguments=0) at Modules/python.cxx:2431
#12 0x0000555555651106 in PYTHON::functionWrapper (this=0x555555720c30, n=0x555555bc6570) at Modules/python.cxx:3224
#13 0x0000555555610ed7 in Language::globalfunctionHandler (this=0x555555720c30, n=0x555555bc6570) at Modules/lang.cxx:1154
#14 0x0000555555613789 in Language::functionHandler (this=0x555555720c30, n=0x555555bc6570) at Modules/lang.cxx:1074
#15 0x00005555556182c4 in Language::cDeclaration (this=0x555555720c30, n=0x555555bc6570) at Modules/lang.cxx:1010
#16 0x000055555560f620 in Dispatcher::emit_one (this=this@entry=0x555555720c30, n=n@entry=0x555555bc6570) at Modules/lang.cxx:118
#17 0x0000555555611b47 in Language::emit_one (n=0x555555bc6570, this=0x555555720c30) at Modules/lang.cxx:395
#18 Language::emit_one (this=0x555555720c30, n=0x555555bc6570) at Modules/lang.cxx:372
#19 0x000055555560fb6d in Dispatcher::emit_children (this=0x555555720c30, n=<optimized out>) at Modules/lang.cxx:210
#20 0x000055555560f3ba in Language::includeDirective (this=<optimized out>, n=<optimized out>) at Modules/lang.cxx:646
#21 0x000055555560f997 in Dispatcher::emit_one (this=this@entry=0x555555720c30, n=n@entry=0x555555bc6350) at Modules/lang.cxx:164
#22 0x0000555555611b47 in Language::emit_one (n=0x555555bc6350, this=0x555555720c30) at Modules/lang.cxx:395
#23 Language::emit_one (this=0x555555720c30, n=0x555555bc6350) at Modules/lang.cxx:372
#24 0x000055555560fb6d in Dispatcher::emit_children (this=0x555555720c30, n=<optimized out>) at Modules/lang.cxx:210
#25 0x000055555565ac4e in PYTHON::top (this=0x555555720c30, n=0x7ffff7952770) at Modules/python.cxx:793
#26 0x000055555562331d in SWIG_main (argc=<optimized out>, argv=<optimized out>, tlm=0x5555557082a0 <modules+672>) at Modules/main.cxx:1326
#27 0x0000555555572951 in main (margc=<optimized out>, margv=<optimized out>) at Modules/swigmain.cxx:271
```

`%ignore`ing the respective function is okay as workaround. Putting `#ifndef SWIG` around the offending doxygen comment seems not to work.

**Comment by gieseanw** [comment]
I believe I have encountered the same bug in a different form.

The segfault happens when

 - @param is used
 - there is at least one actual parameter in the function, and
 - the name of the @param does not match any of the actual parameter names (case-insensitive)


Examples:

    %inline %{
    struct Foo
    {
       //! @param baz
      void Bar(int){return;}
    };
    %}

    %inline %{
    struct Foo
    {
       //! @param int : represents a frozzle
      void Bar(int){return;}
    };
    %}

Curiously, if there are no parameters in the function at all, then the unmatched @param does not crash SWIG. Also, it works if a case-insensitive match exists like so;

    %inline %{
    struct Foo
    {
       //! @param baz
      void Bar(int Baz){return;}
    };
    %}

**Comment by mcfarljm** [comment]
The problem is that it is dereferencing a null pointer when there is no type associated with an item in the parameter list.  I have a fix, and I just need to add some test cases and then I will submit a pull request.

**Comment by dweindl** [comment]
Great! Thanks for looking into that, @mcfarljm.

**Comment by wsfulton** [comment]
I had to also add this change after merging in #1681: 6e240e8
