### ISSUE TITLE
Missing definition for std::size_t when targeting Python?

### ISSUE THREAD

**Issue by lballabio** [swig/swig#1712]
The test file 

```
%module test

%{
std::vector<std::size_t> bar(std::vector<std::size_t>);
%}

%include std_vector.i

%template() std::vector<std::size_t>;

std::vector<std::size_t> bar(std::vector<std::size_t>);
```

has SWIG complaining that 

```
foo.i:12: Warning 490: Fragment 'SWIG_AsVal_std_size_t' not found.
foo.i:12: Warning 490: Fragment 'SWIG_From_std_size_t' not found.
```

and indeed compilation fails because those functions are missing.

I'm guessing I'm missing a definition of `std::size_t`; and indeed, if I tell SWIG something like

```
namespace std {
    typedef ::size_t size_t;
}
```

the wrappers are generated without warning and compile.  Is this what I'm supposed to do, or is there any definition of `std::size_t` in some library file that I should be including?

**Comment by wsfulton** [comment]
That seems a reasonable workaround for what is essentially missing type information. `std::size_t` is only available in the C++ header `cstddef`. SWIG doesn't provide a cstddef.i library file for this but probably should.

Similar to #1557.

**Comment by ojwb** [comment]
It looks like we provide `std::size_t` for most target languages in the library files, but not for Python:

```
$ git grep '%apply.*std::size_t' Lib
Lib/c/std_common.i:%apply size_t { std::size_t };
Lib/c/std_common.i:%apply const size_t& { const std::size_t & };
Lib/csharp/std_common.i:%apply size_t { std::size_t };
Lib/csharp/std_common.i:%apply const size_t& { const std::size_t& };
Lib/d/std_common.i:%apply size_t { std::size_t };
Lib/d/std_common.i:%apply const size_t& { const std::size_t& };
Lib/go/std_common.i:%apply size_t { std::size_t };
Lib/go/std_common.i:%apply const size_t& { const std::size_t& };
Lib/guile/std_common.i:%apply size_t { std::size_t };
Lib/java/std_common.i:%apply size_t { std::size_t };
Lib/java/std_common.i:%apply const size_t& { const std::size_t& };
Lib/javascript/jsc/std_common.i:%apply size_t { std::size_t };
Lib/javascript/jsc/std_common.i:%apply const size_t& { const std::size_t& };
Lib/javascript/napi/std_common.i:%apply size_t { std::size_t };
Lib/javascript/napi/std_common.i:%apply const size_t& { const std::size_t& };
Lib/javascript/v8/std_common.i:%apply size_t { std::size_t };
Lib/javascript/v8/std_common.i:%apply const size_t& { const std::size_t& };
Lib/lua/std_common.i:%apply size_t { std::size_t };
Lib/lua/std_common.i:%apply const size_t& { const std::size_t& };
Lib/ocaml/std_common.i:%apply size_t { std::size_t };
Lib/ocaml/std_common.i:%apply const size_t& { const std::size_t& };
Lib/perl5/std_common.i:%apply size_t { std::size_t };
Lib/php/std_common.i:%apply size_t { std::size_t };
Lib/tcl/std_common.i:%apply size_t { std::size_t };
Lib/tcl/std_common.i:%apply const unsigned long& { const std::size_t& };
Lib/typemaps/misctypes.swg:%apply size_t { std::size_t };
Lib/typemaps/misctypes.swg:%apply const size_t& { const std::size_t& };
Lib/typemaps/misctypes.swg:%apply size_t& { std::size_t& };
Lib/typemaps/typemaps.swg:%apply size_t& { std::size_t& };
```

It seems we used to have it but it got lost in the "massive typemap unification" (7e5e4fd1f9c8adfcd0eb1328e35143e110e115ff - 20 years ago tomorrow!)

Oddly we seem to have a generic version (`Lib/typemaps/misctypes.swg`) but it's only included by `scilab`.

Anyway, I think we should add (or restore) this for Python.

**Comment by wsfulton** [comment]
Yes, let's add this to python and the testcase. @ojwb, could you do in next 24 hours (sorry for last minute push), but would like to include it in release.

**Comment by ojwb** [comment]
I'll take a look

**Comment by ojwb** [comment]
Checking the list of grep matches above the following target languages may to be missing this too: octave r ruby

Perhaps they address this a different way, but if we get this going for Python we should carefully check these too.

However, the `%apply` approach that seems to be the usual way to handle this doesn't trivially work for Python - with the testcase here we then get:

```
test.i:12: Warning 490: Fragment 'SWIG_AsVal_std_size_t' not found.
test.i:12: Warning 490: Fragment 'SWIG_From_std_size_t' not found.
```

Using the typedef approach shown above instead causes the `complextest` testcase to fail with a segfault.

I'll poke some more, but it's not as simple as one might expect.

**Comment by wsfulton** [comment]
If it isn't simple, we'll have to leave it to after the 4.4.0 release then.

**Comment by ojwb** [comment]
> Checking the list of grep matches above the following target languages may to be missing this too: octave r ruby

The fragments are missing with these too, and also for scilab:

```
$ ../preinst-swig -c++ -octave test.i
test.i:12: Warning 490: Fragment 'SWIG_AsVal_std_size_t' not found.
test.i:12: Warning 490: Fragment 'SWIG_From_std_size_t' not found.
$ ../preinst-swig -c++ -r test.i
test.i:12: Warning 490: Fragment 'SWIG_AsVal_std_size_t' not found.
test.i:12: Warning 490: Fragment 'SWIG_From_std_size_t' not found.
$ ../preinst-swig -c++ -ruby test.i
test.i:12: Warning 490: Fragment 'SWIG_AsVal_std_size_t' not found.
test.i:12: Warning 490: Fragment 'SWIG_From_std_size_t' not found.
$ ../preinst-swig -c++ -scilab test.i
test.i:12: Warning 490: Fragment 'SWIG_AsVal_std_size_t' not found.
test.i:12: Warning 490: Fragment 'SWIG_From_std_size_t' not found.
```

Looking just at Python for now, those missing fragments are expanded by this in `Lib/python/std_common.i`:

```
/*  
  Generate the traits for a 'primitive' type, such as 'double',  
  for which the SWIG_AsVal and SWIG_From methods are already defined.  
*/  

%define %traits_ptypen(Type...)  
  %fragment(SWIG_Traits_frag(Type),"header",  
            fragment=SWIG_AsVal_frag(Type),  
            fragment=SWIG_From_frag(Type),  
            fragment="StdTraits") {  
```

via:

```
//  
// Generates the traits for all the known primitive  
// C++ types (int, double, ...)  
//  
%apply_cpptypes(%traits_ptypen);
```

and that macro **does** include `std::size_t`:

```
/* apply the Macro(Type) to all  C++ types  */
%define %apply_cpptypes(Macro, Arg2...)
%apply_ctypes(Macro, Arg2)
_apply_macro(Macro, std::size_t, Arg2);
_apply_macro(Macro, std::ptrdiff_t, Arg2);
_apply_macro(Macro, std::string, Arg2);
_apply_macro(Macro, std::wstring, Arg2);
_apply_macro(Macro, std::complex<float>, Arg2);
_apply_macro(Macro, std::complex<double>, Arg2);
%enddef
```

So that's why it's getting required, but I don't see where it gets provided by target languages where this seems to work.

Looking at the `typedef` approach, it seems `complextest` runs into infinite recursion in `SwigType_type()` - backtrace from gdb:

```
#0  _int_malloc (av=av@entry=0x7ffff7bf1ac0 <main_arena>, bytes=bytes@entry=24)
    at ./malloc/malloc.c:4128
#1  0x00007ffff7aacd52 in __GI___libc_malloc (bytes=bytes@entry=24)
    at ./malloc/malloc.c:3406
#2  0x0000555555595499 in DohMalloc (size=size@entry=24) at DOH/memory.c:269
#3  0x000055555559436a in NewNode (k=0x7fffefb5c270, obj=0x7fffefb57910)
    at DOH/hash.c:88
#4  Hash_setattr (ho=<optimized out>, k=0x7fffefb5c270, obj=0x7fffefb57910)
    at DOH/hash.c:236
#5  0x000055555559476f in CopyHash (ho=<optimized out>) at DOH/hash.c:490
#6  0x00005555555910bc in DohCopy (obj=0x7fffefb60b10) at DOH/base.c:63
#7  0x00005555555910d7 in DohCopy (obj=obj@entry=0x7fffefb60bd0)
    at DOH/base.c:65
#8  0x00005555556c6edc in SwigType_typedef_resolve (t=0x7ffff06094d0)
    at Swig/typesys.c:705
#9  0x00005555556c82e9 in SwigType_istypedef (t=<optimized out>)
    at Swig/typesys.c:1268
#10 0x00005555556c8939 in SwigType_type (t=t@entry=0x7ffff06094d0)
    at Swig/typesys.c:1485
#11 0x00005555556c8955 in SwigType_type (t=t@entry=0x7ffff0609490)
    at Swig/typesys.c:1488
#12 0x00005555556c8955 in SwigType_type (t=t@entry=0x7ffff0609450)
    at Swig/typesys.c:1488
```
[snip]
```
#174639 0x00005555556c8955 in SwigType_type (t=t@entry=0x7fffefb608f0)
    at Swig/typesys.c:1488
#174640 0x00005555556c8955 in SwigType_type (t=t@entry=0x7fffefb51090)
    at Swig/typesys.c:1488
#174641 0x00005555556b31e8 in ParmList_numrequired (p=0x7fffefb51070)
    at Swig/parms.c:204
#174642 0x00005555555dd46b in Allocate::constructorDeclaration (
    this=0x555555f80130, n=0x7fffefb50f70) at Modules/allocate.cxx:1305
#174643 0x00005555556402df in Dispatcher::emit_one (this=0x555555f80130, 
    n=0x7fffefb50f70) at Modules/lang.cxx:137
#174644 0x00005555556406bd in Dispatcher::emit_children (this=0x555555f80130, 
    n=<optimized out>) at Modules/lang.cxx:217
#174645 0x00005555555e01bc in Allocate::classDeclaration (this=0x555555f80130, 
    n=0x7fffefb42eb0) at Modules/allocate.cxx:792
#174646 0x0000555555640291 in Dispatcher::emit_one (this=0x555555f80130, 
    n=0x7fffefb42eb0) at Modules/lang.cxx:133
#174647 0x00005555556406bd in Dispatcher::emit_children (this=0x555555f80130, 
    n=<optimized out>) at Modules/lang.cxx:217
#174648 0x000055555564037b in Dispatcher::emit_one (this=0x555555f80130, 
    n=0x7fffefb42b10) at Modules/lang.cxx:145
#174649 0x00005555556406bd in Dispatcher::emit_children (this=0x555555f80130, 
    n=<optimized out>) at Modules/lang.cxx:217
#174650 0x00005555556404e9 in Dispatcher::emit_one (this=0x555555f80130, 
    n=0x7fffefa71070) at Modules/lang.cxx:171
#174651 0x00005555556406bd in Dispatcher::emit_children (
    this=this@entry=0x555555f80130, n=<optimized out>) at Modules/lang.cxx:217
#174652 0x00005555555dc1ba in Allocate::top (this=0x555555f80130, 
    n=<optimized out>) at Modules/allocate.cxx:731
#174653 Swig_default_allocators (n=<optimized out>)
    at Modules/allocate.cxx:1603
#174654 0x000055555564f65d in SWIG_main (argc=<optimized out>, 
    argv=<optimized out>, tlm=0x555555733680 <modules+640>)
    at Modules/main.cxx:1211
#174655 0x00007ffff7a33ca8 in __libc_start_call_main (
    main=main@entry=0x555555572f00 <main(int, char**)>, argc=argc@entry=9, 
    argv=argv@entry=0x7fffffffde28)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#174656 0x00007ffff7a33d65 in __libc_start_main_impl (
    main=0x555555572f00 <main(int, char**)>, argc=9, argv=0x7fffffffde28, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffde18) at ../csu/libc-start.c:360
#174657 0x00005555555737b1 in _start ()
```

That looks like a bug in itself, though I failed to find a way to trigger it with `namespace std { typedef ::size_t size_t; }` in a user interface file.

> If it isn't simple, we'll have to leave it to after the 4.4.0 release then.

I think it's beyond what I can deal with today, but if the above makes it obvious to you I'd be happy to have it fixed.

Otherwise I think postponing it would be OK - it's been broken for 20 years and is easy to workaround.

**Comment by wsfulton** [comment]
We'll postpone fixing this then. Thanks for looking.
