### ISSUE TITLE
cvar has no attribute '__class__'

### ISSUE THREAD

**Issue by mthcrts** [swig/swig#2012]
Build Python example from the tutorial and run:

```python
$ python
>>> import example
>>> import abc
>>> isinstance(example.cvar, abc.ABC)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/abc.py", line 183, in __instancecheck__
    subclass = instance.__class__
AttributeError: Unknown C global variable '__class__'
```

I will emit a similar issue into the Python bugtracker for the abc module that should probably check the attribute existence.
But I also think that every Python class must have a such attribute.

**Comment by mthcrts** [comment]
that's fixed in python3.7
