### ISSUE TITLE
C++ uses python functions encapsulated by swig

### ISSUE THREAD

**Issue by flyskyosg** [swig/swig#2028]
I have a simple C++ function takes a std::vector as an argument that I am wrapping with SWIG for Python. 
I want to use c++ to call the python-encapsulated function, but some errors occur.
I don’t know how to pass the parameters, Could you give me some suggestions?

The example code is below.

// AAA.h
```
#ifndef __AAA_H_
#define __AAA_H_

#include <iostream>
#include <vector>

int TAdd(const std::vector<float>& vTempVector);

#endif
```
// AAA.cpp
```
#include "AAA.h"

int TAdd(const std::vector<float>& vTempVector)
{
	int nSize = vTempVector.size();
	for (int i = 0; i < nSize; i++)
	{
		std::cout << vTempVector[i] << std::endl;
	}
	return nSize + 10;
}
```
```
/* File : testAAA.i */
%module testAAA
%include "std_vector.i"
%{

#include "AAA.h"
%}

%include "AAA.h"

%template(VectorFloat) std::vector<float>;
```

C++ uses python functions:
```
	PyObject* pv = PyObject_GetAttrString(pModule, "TAdd");
	if (!pv || !PyCallable_Check(pv))
	{
		std::cout << "Can't Find Funftion" << std::endl;
		return;
	}

	std::vector<double> vTempInt;
	vTempInt.push_back(11.11);
	vTempInt.push_back(22.11);
	vTempInt.push_back(33.11);
	vTempInt.push_back(44.11);

	PyObject* pyList = PyList_New(4);
	PyList_SetItem(pyList, 0, PyFloat_FromDouble(vTempInt[0]));
	PyList_SetItem(pyList, 1, PyFloat_FromDouble(vTempInt[1]));
	PyList_SetItem(pyList, 2, PyFloat_FromDouble(vTempInt[2]));
	PyList_SetItem(pyList, 3, PyFloat_FromDouble(vTempInt[3]));

	PyObject* pArgList = PyTuple_New(1);
	int nValue = PyTuple_SetItem(pArgList, 0, pyList);
	std::cout << nValue << std::endl;

	PyObject* pRet = PyObject_CallObject(pv, pArgList );

	if (pRet)
	{
		long result = PyLong_AsLong(pRet);
		std::cout << "result:" << result << std::endl;
	}
```
![image](https://user-images.githubusercontent.com/6902466/119755147-1cc5c780-bed4-11eb-927a-cb204e27c49c.png)

**Comment by ojwb** [comment]
Since you're calling from C++, why not just call `Tadd(vTempInt)` directly rather than trying to bounce the call via Python?

**Comment by ojwb** [comment]
Anyway, your C++ looks to be equivalent to this Python:

```
>>> import testAAA
>>> x = [11.11, 22.11, 33.11, 44.11]
>>> testAAA.TAdd(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/olly/git/swig/gh2028/testAAA.py", line 127, in TAdd
    return _testAAA.TAdd(vTempVector)
TypeError: in method 'TAdd', argument 1 of type 'std::vector< float,std::allocator< float > > const &'
>>>
```

The Python equivalent which actually works would be:

```
>>> x = testAAA.VectorFloat()
>>> for v in [11.11, 22.11, 33.11, 44.11]: x.append(v)
... 
>>> testAAA.TAdd(x)
11.11
22.11
33.11
44.11
14
>>>
```

If you really want to do this via Python, that's what you need to replicate.

Not a SWIG bug so closing.
