### ISSUE TITLE
Python: using the -builtin option doesn't work when using multiple embedded interpreters

### ISSUE THREAD

**Issue by jsenn** [swig/swig#2114]
This is similar to #2101. We use SWIG to allow users to interact with our SDK by writing Python scripts from within the UI of our application. Each time a user runs a script, a new Python interpreter is created, the extension module is imported, and then the script is run. All of this happens within our application's main process. This looks roughly like the following:

```c++
#include <Python.h>

extern "C"
{
PyObject* PyInit__test(void);
}

void
RunScript( const char* script )
{
	int importSucceeded = PyImport_AppendInittab( "_test", &PyInit__test ); // Import extension module

	Py_Initialize();
	int result = PyRun_SimpleString( script );
	Py_Finalize();
}
```
Our wrapped code looks like the following:
```c++
// Test.h
class Test
{
    static int Get1();
};
```
```c++
// Test.cpp
#include Test.h
int Test::Get1() { return 1; }
```
```
// test.i
%module test
%{
#include "Test.h"
%}

%include "Test.h"
```

Having run swig with the `-builtin` flag, if you call `RunScript()` with the script `import test; print(test.Test.Get1())` once it succeeds, but if you do it again, you'll get the following output:
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
AttributeError: type object 'test.Test' has no attribute 'Get1'
```
For some reason the `Get1` function is no longer visible to the interpreter. Note that the same thing happens with non-static member functions.

I wasn't able to track this one down, but @wsfulton [suggested](https://github.com/swig/swig/pull/2102#issuecomment-984447459) in #2102 there may be issues with `SwigPyPacked_type`, which is involved in holding member function pointers, so that may be a good place to look.

**Comment by wsfulton** [comment]
For the record, I replicated this by using your first block of code in a file cpprun.cxx with the addition of:
```c++
int main() {
  RunScript("import test; print(test.Test.Get1())");
  RunScript("import test; print(test.Test.Get1())");
  return 0;
}
```
and building
```bash
env SWIG_LIB=$HOME/swig/swig-4.3.1/Lib  $HOME/swig/swig-4.3.1/swig -python -builtin -c++  -o test_wrap.cxx test.i
g++ -g -c -fPIC -I.  -I/usr/include -std=c++20  test_wrap.cxx  Test.cpp   -I/usr/include/python3.12 -I/usr/include/python3.12 # -DSWIG_REFCNT_DEBUG
g++ -shared -g -I/usr/include -std=c++20    Test.o test_wrap.o    -o _test.so
rm -f libtest.so
ln -s _test.so libtest.so
g++ -g -I/usr/include/python3.12 -I/usr/include/python3.12 cpprun.cxx -L. -lpython3.12 -ltest -o ./cpprun
env LD_LIBRARY_PATH=. PYTHONPATH=.  ./cpprun
1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: type object 'test.Test' has no attribute 'Get1'
Finished main
```

Closing as fixed with the switch to heap types in #3196. The re-initialization was not well designed with the static types as it relied on a few singletons using static variables and I think deficiencies in this design was the main cause of the problem for multiple imports.
