### ISSUE TITLE
swig -python: writing to non-existing C struct entries does not throw an error (only reading does)

### ISSUE THREAD

**Issue by hbkoenig** [swig/swig#2215]
Hi Swig/Python developers!

we're using "swig" to create a python wrapper for a C library to describe and access
some 16 bit hardware registers which, in C, are defined like this (see reg.h):
```
typedef struct {
  uint16_t chip_id       : 8;
  uint16_t rev_id_minor  : 4;
  uint16_t rev_id_major  : 4;
} ASIC_ID_t; // Chip identification code

typedef union{
        uint16_t value;
        ASIC_ID_t ASIC_ID;
} reg_t;
```

the wrapper code created by swig allows to access e.g. "reg.ASIC_ID.chip_id"

this works fine for read access / getter, as there will be errors for invalid elements in "ASIC_ID", like reg.ASIC_ID.xxx"
BUT writing to such invalid elements does not give an error but silently fails without any effect:-(

how can we get errors for invalid register elements ???

minimal working example & test code:

if you have "make" you can run all steps with "make ..." (see usage without argument).

"make test" runs:
        cmake -B build
        cmake --build build
        python3 reg_test.py

which finally prints this message which should NOT happen (see code in reg.py)

        FAILED: no error trying to set non-existing ASIC_ID.xxx :-(

in order to catch theses invalid accesses to nonexisting fields/elements,
we've played around with __setaddr__() and similar -- so far without success;-(

we've tried to add __setattr__() to the register object to check if register bits names exist in structure
and throw AttributeError(f"{key} does not exist") if not,
see setter.py or reg+setter.py (or reg.py.diff)

"make test_setter" will copy and run this code like this
        cp reg+setter.py reg.py
        python3 reg_test.py
 but this fails for normal/working write accesses with

```
Traceback (most recent call last):
  File "/home/koh8rt/swig/reg/reg_test.py", line 7, in <module>
    reg.ASIC_ID.chip_id = 0xfe
  File "/home/koh8rt/swig/reg/reg.py", line 84, in __setattr__
    return self.__class__.__dict__[key].fset(self,value)
TypeError: in method 'ASIC_ID_t_chip_id_set', argument 1 of type 'ASIC_ID_t *'
make[1]: *** [Makefile:34: py_test] Error 1
```
how to I have to call _setattr__() or fset() or whatever to make the set-value operation work for this register classes ?

trying to use __slots__... (again see reg+setter.py) results in 

ValueError: 'chip_id' in __slots__ conflicts with class variable

right now the python wrapper created for this register access class
is very dangerous to use, because any typos, cut'n'paste error
(or later changes in the register namings!) are NOT trapped
when running python code with invalid register fields/bits names...

PLEASE help to make this python wrapper usable!

thanks!! 
Harald

**Comment by ojwb** [comment]
Sounds like you want `%pythonnondynamic`.

**Comment by ojwb** [comment]
The ability to add arbitrary attributes to classes is a standard Python feature:

```
>>> class X:
...     def __init__(x):
...         pass
... 
>>> x = X()
>>> x.chip_id = 1
```

So it's not a SWIG bug that this is possible by default in SWIG-wrapped Python classes as well as it's the behaviour which a Python programmer would naturally expect.  You should be able to change that with `%pythonnondynamic`, therefore closing.

**Comment by hbkoenig** [comment]
thanks for that pointer -- exactly what I was looking for!!  works like a charm!

it would be nice to be able to have some generic declaration with pattern matching like
```
%pythonnondynamic chip_*_t;
```
as a catch-all for all register descriptions -- but it's easy to create such an explicit list with external tools...

one more question/comment to the original behavior and now learning from the keyword "pythonnondynamic" that this indeed is supposed to be "dynamic" in some sense (as I would have expected;)

this [expected] "dynamic" behavior does not work as expected for the code generated by swig:

while it's possible to assign new elements like this 
```
>>> reg.ASIC_ID.new = 0x1234
```
these "new" elements cannot be accessed:
```
>>> reg.ASIC_ID.new
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ASIC_ID_t' object has no attribute 'new'

```
and they do not show up as "expected" (thinking of dynamically adding elements like for python objects/classes):
```
>>> dir(reg.ASIC_ID)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__weakref__', 'chip_id', 'rev_id_major', 'rev_id_minor', 'this', 'thisown']

```

so the default behavior is at least unexpected and somewhat inconsistent (not to say buggy?;-)

but thanks again a lot for your great and quick help!!
Harald

**Comment by ojwb** [comment]
There's `regexmatch` but I think that's only available for `%rename` and `%ignore`, not arbitrary features - `%pythonnondynamic` is really just an alias for a `%feature`:

```
#define %pythonnondynamic      %feature("python:nondynamic", "1")
```

It seems `regexmatch` would make sense for `%feature` too.

> these "new" elements cannot be accessed:

I'd expect such set values to be readable too.  I'm not familiar with all the details of SWIG/Python but at a guess there's a custom getattr in play which fails to fall back to Python's default getattr handling.

Can you open new issues for each of those?

**Comment by hbkoenig** [comment]
> thanks for that pointer -- exactly what I was looking for!! works like a charm!

only now I noticed that `%pythonnondynamic ASIC_ID_t;` has a huge drawback:
completions for those existing struct elements do not work anymore:-(

without `%pythonnondynamic ASIC_ID_t;`, typing `reg.ASIC_ID.ch<TAB>` 
will expand to `reg.ASIC_ID.chip_id`, and `dir(reg.ASIC_ID)` shows the dict:
```
>>> dir(reg.ASIC_ID)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__weakref__', 'chip_id', 'rev_id_major', 'rev_id_minor', 'this', 'thisown']
```

but with `%pythonnondynamic ASIC_ID_t;`, typing `reg.ASIC_ID.ch<TAB>` does not expand anymore:-(
and `dir(reg.ASIC_ID)` does not show a dict anymore:
```
>>> dir(reg.ASIC_ID)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor '__dict__' for 'ASIC_ID_t' objects doesn't apply to a 'ASIC_ID_t' object
```

I hope you have a cure for that nasty side effect, too ?!?

**Comment by ojwb** [comment]
Sounds like a bug in `%pythonnondynamic` - I'm a heavy python user, but I'd expect `dir()` to work here.

Reopening and retitling.

**Comment by ojwb** [comment]
Still fails with de7fbae696094b4c03a68d9821e93d887a848287 with the same `TypeError`.

However `dir()` **does** work if the SWIG's `-builtin` option is used.
