### ISSUE TITLE
SIGSEGV on memmove and byte-string with surrogateescape

### ISSUE THREAD

**Issue by ya-mouse** [swig/swig#222]
With swig 2.x and 3.x I've got a segfault on the following python code:

``` python
#!/usr/bin/python3.4
from mm import *

data = b'(\x80\x01\x0833\x00\t\x99\x8332'

u = uint8ary(128)
s = data.decode('utf-8', errors="surrogateescape")
memmove(u, s)
print(u)
```

SWIG source:

``` swig
%module mm

%include "stdint.i"
%include "carrays.i"
%include "cdata.i"
%array_class(uint8_t, uint8ary)
%cdata(uint8_t)
```

Makefile

``` make
CXX=g++
CXXFLAGS=-g -fPIC -DPIC -I/usr/include/python3.4

OBJ=mm_wrap.o

all: _mm.so

_mm.so: $(OBJ)
    $(CXX) -g -shared -Wl,-soname,_mm.so -o $@ $^ $(LIB)

clean:
    rm -f $(OBJ) _mm.so

%_wrap.cxx: %.i
    swig -c++ -python -py3 $<

%.o: %.cxx
    $(CXX) -c $(CXXFLAGS) $<
```

GDB backtrace:

``` gdb
Program received signal SIGSEGV, Segmentation fault.
PyBytes_AsStringAndSize (obj=0x7ffff7f38438, s=0x7fffffffd908, len=0x7fffffffd910)
    at ../Objects/bytesobject.c:560
560    ../Objects/bytesobject.c: No such file or directory.
(gdb) bt
#0  PyBytes_AsStringAndSize (obj=0x7ffff7f38438, s=0x7fffffffd908, len=0x7fffffffd910)
    at ../Objects/bytesobject.c:560
#1  0x00007ffff69dfa0b in SWIG_AsCharPtrAndSize (obj=0x0, cptr=0x7fffffffd978, psize=0x7fffffffd980,
    alloc=0x7fffffffd964) at mm_wrap.cxx:3279
#2  0x00007ffff69dff6a in _wrap_memmove (args=0x7ffff7ef9b88) at mm_wrap.cxx:3475
#3  0x000000000057c7bc in call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at ../Python/ceval.c:4227
#4  PyEval_EvalFrameEx (f=f@entry=0x7ffff7f38438, throwflag=throwflag@entry=0) at ../Python/ceval.c:2829
#5  0x000000000057d3d3 in PyEval_EvalCodeEx (_co=_co@entry=0x7ffff7eca270,
    globals=globals@entry=0x7ffff7f35408, locals=locals@entry=0x7ffff7f35408, args=args@entry=0x0,
    argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=kwcount@entry=0, defs=defs@entry=0x0,
    defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0) at ../Python/ceval.c:3578
```

Within SWIG_AsCharPtrAndSize() the routine PyUnicode_AsUTF8String() returns NULL or strange pointer's value (e.g. decimal 378). Then it just segfaults on PyBytes_AsStringAndSize() call.
**PS**. Python 3.4 (64 bit) on Ubuntu 14.04.

**Comment by wsfulton** [comment]
This seg fault was fixed in pystrings.swg in b0e29fbdf31bb94b11cb8a7cc830b4a76467afa3 for inclusion in swig-4.0.0.
