### ISSUE TITLE
Go tests failed with SWIG 4.1.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2375]
I ran rebuild of SWIG 4.1.0 (commit e97181ebc) on Fedora Rawhide(F38) and Go tests are failing on architectures ppc64le and s390x. 
Details and logs for all architectures are [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=92154329).

Failure on PPC64LE - more tests failed with the same error
```
checking go testcase packageoption
./multi_import_runme: error while loading shared libraries: R_PPC64_ADDR16_HA reloc at 0x000000012a6609b0 for symbol `' out of range
make[1]: *** [Makefile:52: multi_import.multicpptest] Error 127
checking go testcase template_typedef_import
make[1]: Target 'check' not remade because of errors.
make: *** [Makefile:240: check-go-test-suite] Error 1
```
[Complete build log for ppc64le](https://kojipkgs.fedoraproject.org//work/tasks/4399/92154399/build.log)

Failure on S390X - more tests failed with the same error
```
checking go testcase li_std_pair
panic: 0
goroutine 1 [running]:
main.main()
	/builddir/build/BUILD/swig-4.1.0/Examples/test-suite/go/gopath/src/li_std_map/runme/runme.go:28 +0x3b8
make[1]: *** [Makefile:41: li_std_map.cpptest] Error 2
```
[Complete build log for s390x](https://kojipkgs.fedoraproject.org//work/tasks/4400/92154400/build.log)

**Comment by ojwb** [comment]
@ianlancetaylor Please could you take a look.

**Comment by jschueller** [comment]
@jplesnik does swig 4.0.2 tests all pass with that version of go on these arch ?

**Comment by jplesnik** [comment]
@jschueller 
swig 4.0.2 fails with the same error for ppc64le. For s390x, it also fails, bout with different errors [- check the log](https://koji.fedoraproject.org/koji/taskinfo?taskID=92245631).

**Comment by ojwb** [comment]
So not a regression at least, though obviously it'd be better if it worked on all architectures.

The ppc64le error sounds like maybe it's using a relocation type with too short a range - `R_PPC64_ADDR16_HA` sounds like a 16 bit offset.  If so that's probably a Go toolchain problem rather than a SWIG one.

I've no idea what the s390x error might mean.

**Comment by ojwb** [comment]
I tested current git master (06296a71281f049cfc438b4a7fb05127a0474144) on the Debian s390x porterbox with unstable (which has `go version go1.19.2 linux/s390x`) and I see the same failure for `li_std_map.cpptest` there so that seems to not be distro-specific.

However, on the Debian ppc64el porterbox (same versions) `multi_import.multicpptest` passes for me, so that problem may be specific to Fedora.  I tried `make check-go-test-suite` and the only failures were because I hadn't bothered to install boost.

@jplesnik Searching for the ppc64le error message found me https://www.mail-archive.com/golang@lists.fedoraproject.org/msg13204.html which was meant to have been fixed a while ago, but maybe you can check if that fix got reverted?  Could be a different problem causing the same error message of course...

**Comment by ojwb** [comment]
@jplesnik Are you still seeing these?

**Comment by jplesnik** [comment]
@ojwb I tested rebuild of swig from current git master (https://github.com/swig/swig/commit/06296a71281f049cfc438b4a7fb05127a0474144) and there is a result:
https://koji.fedoraproject.org/koji/taskinfo?taskID=100478851

I enabled only Go tests for this run. Fedora Rawhide contains `Go 1.20.2`. I got the same errors as I reported.

**Comment by ojwb** [comment]
@jplesnik Might be worth a retest as it's been more than 2 years and there have been several new Go releases.

**Comment by jplesnik** [comment]
@ojwb I used git master (de7fbae69) for rebuild and it failed again on s390x and ppc64le:
https://koji.fedoraproject.org/koji/taskinfo?taskID=134104524

I enabled only Go tests for this run. Fedora Rawhide contains Go 1.24.4. I got the same errors as I reported.

**Comment by ojwb** [comment]
Oh well, thanks for retesting.

The ppc64le problem still reads like a compiler flags problem resulting in too small a location being used to me (perhaps related to https://www.mail-archive.com/golang@lists.fedoraproject.org/msg13204.html).

There are a lot of warnings from that build too, most of which seem to look like:

```
/builddir/build/BUILD/swig-4.4.0-build/swig-4.4.0/Examples/test-suite/go/gopath/src/go_inout/go_inout.go:52:13: warning: type of ‘_wrap_putuint64_go_inout_050d1b0d25c3fc9b’ does not match original declaration [-Wlto-type-mismatch]
   52 | extern void _wrap_putuint64_go_inout_050d1b0d25c3fc9b(uintptr_t arg1, swig_type_4 arg2, uintptr_t arg3);
      |             ^
../go_inout_wrap.cxx:590:6: note: type mismatch in parameter 1
  590 | void _wrap_putuint64_go_inout_050d1b0d25c3fc9b(std::string *_swig_go_0, long long _swig_go_1, uint64_t *_swig_go_2) {
      |      ^
../go_inout_wrap.cxx:590:6: note: ‘_wrap_putuint64_go_inout_050d1b0d25c3fc9b’ was previously declared here
../go_inout_wrap.cxx:590:6: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
```

There are similar warnings in the s390x log.

I guess it's intentional as we're passing a pointer for a `uintptr_t` parameter, but apparently these warnings mean the generated code isn't currently safe to compile with `-flto`.  I'd suggest turning off that option for now and seeing if that helps.

**Comment by erezgeva** [comment]
Did you check?
https://go.dev/wiki/MinimumRequirements#ppc64le-little-endian
And
https://go.dev/wiki/MinimumRequirements#s390x
