### ISSUE TITLE
libsbml test failed with SWIG 4.1.0

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#2378]
I am testing rebuild of SWIG dependencies against version 4.1.0 in Fedora rawhide/38.

The test of `libSBML-5.19.0` is failing with this version.
```
35: Test command: /usr/bin/python3 "/builddir/build/BUILD/libSBML-5.19.0-Source/examples/python/append_to_note.py" "/builddir/build/BUILD/libSBML-5.19.0-Source/examples/sample-models/from-spec/level-3/enzymekineticext.xml" "veq" "a new note" "append_to_note.out.xml"
35: Working Directory: /builddir/build/BUILD/libSBML-5.19.0-Source/build/src/bindings/python
35: Environment variables: 
35:  PYTHONPATH=/builddir/build/BUILD/libSBML-5.19.0-Source/build/src/bindings/python:/builddir/build/BUILD/libSBML-5.19.0-Source/build/src/bindings/python:
35: Test timeout computed to be: 3000
35: Body before change: 
35: <body xmlns="http://www.w3.org/1999/xhtml">
35:   <p xmlns="http://www.w3.org/1999/xhtml">Some notes</p>
35: </body>
35: Traceback (most recent call last):
35:   File "/builddir/build/BUILD/libSBML-5.19.0-Source/examples/python/append_to_note.py", line 95, in <module>
35:     addToNotes(doc, sys.argv[2], sys.argv[3])
35:   File "/builddir/build/BUILD/libSBML-5.19.0-Source/examples/python/append_to_note.py", line 78, in addToNotes
35:     body.addChild(libsbml.XMLNode_convertStringToXMLNode(stringToAdd))
35:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
35: AttributeError: module 'libsbml' has no attribute 'XMLNode_convertStringToXMLNode'
35/68 Test #35: test_python_append_to_note ....................***Failed    0.13 sec
```

Complete log is [here](https://download.copr.fedorainfracloud.org/results/jplesnik/swig-rebuild/fedora-rawhide-x86_64/04863226-libsbml/builder-live.log.gz).

**Comment by jschueller** [comment]
probably same as #2376

**Comment by jplesnik** [comment]
The solution mention in #2376 also work for libsbml. Thank you
