### ISSUE TITLE
C++ std::unordered_set does not accept Python set objects

### ISSUE THREAD

**Issue by fuzihaofzh** [swig/swig#2515]
This is a known issue. I also encountered this problem. The details are at https://stackoverflow.com/questions/73900661/using-swig-python-wrapper-argument-2-of-type-stdunordered-set-stdstring .
Some Demo code from the StackOverflow page:

test.i
```python
%module test

// Code injected into wrapper
%{
#include <iostream>
#include <string>
#include <unordered_set>

// Function using the parameter type from OP error message
void func(std::unordered_set<std::string> const &string_set) {
    for(auto& s : string_set)
        std::cout << s << std::endl;
}
%}

// SWIG support for templates
%include <std_unordered_set.i>
%include <std_string.i>
// Must instantiate the specific template used
%template(string_set) std::unordered_set<std::string>;

// Tell SWIG to wrap the function
void func(std::unordered_set<std::string> const &string_set);
```

Demo
```python
>>> import test
>>> test.func(['abc','def','abc','ghi'])  # list works
abc
def
ghi
>>> s = test.string_set(['aaa','bbb','ccc','aaa','bbb'])
>>> test.func(s)
aaa
bbb
ccc
>>> s = test.string_set(('aaa','bbb','ccc','aaa','bbb')) # tuple works
>>> list(s)
['aaa', 'bbb', 'ccc']
>>> test.func({'abc','def'})  # set doesn't work
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\test.py", line 194, in func
    return _test.func(string_set)
TypeError: in method 'func', argument 1 of type 'std::unordered_set< std::string,std::hash< std::string >,std::equal_to< std::string >,std::allocator< std::string > > const &'
```

Is it possible somehow make it possible to directly pass python set as initialization of unordered_set? Thanks!

**Comment by wsfulton** [comment]
The implementation uses Python's Sequence protocol as a common implementation for converting Python containers into all of the STL containers. Python's sets do not implement the Sequence protocol, but just about every other Python container does. I've been experimenting with Python's Iterator protocol as an alternative / enhancement and hope to add this in soon.
