### ISSUE TITLE
Invalid bindings generated for protected virtual method with default arguments

### ISSUE THREAD

**Issue by micahdlamb** [swig/swig#2555]
I'm getting bad bindings generated for this simple usecase:
```cpp
class Base {
protected:
	virtual void test(int x = 0) {}
};

class Derived : public Base {};
```

%director Base;
%director Derived;

In the wrap file it correctly generates this method:
**_wrap_Derived_test__SWIG_1**

But **_wrap_Derived_test** is incorrectly calling **_wrap_Base_test__SWIG_1** which crashes.

```cpp
SWIGINTERN PyObject *_wrap_Derived_test(PyObject *self, PyObject *args) {
      //...
      return _wrap_Base_test__SWIG_1(self, argc, argv);
}

**Comment by wsfulton** [comment]
I cannot replicate this. Please modify the following to replicate:
```swig
%module(directors="1") example

%feature("director") Base;
%feature("director") Derived;

%inline %{
#include <iostream>
class Base {
protected:
  virtual void test(int x = 0) {
    std::cout << "Base::test " << x << std::endl;
  }
public:
  static void call_test(Base *b) {
    b->test();
    b->test(555);
  }
};

class Derived : public Base {};
%}
```

```python
from example import *

class MyDerived(Base):

    def __init__(self):
        Base.__init__(self)

    def test(self, x=0):
        print("In MyDerived.test {}".format(x))
        return

d = MyDerived()
d.test()
d.test(123)
Base.call_test(d)

d = Derived()
Base.call_test(d)
d.test()  # RuntimeError: accessing protected member test
```
Output:
```
In MyDerived.test 0
In MyDerived.test 123
In MyDerived.test 0
In MyDerived.test 555
Base::test 0
Base::test 555
Traceback (most recent call last):
  File "runme.py", line 19, in <module>
    d.test()  # RuntimeError: accessing protected member test
  File "example.py", line 105, in test
    return _example.Derived_test(self, x)
RuntimeError: accessing protected member test
../../Makefile:1323: recipe for target 'python_run' failed
make[1]: *** [python_run] Error 1
Makefile:11: recipe for target 'check' failed
make: *** [check] Error 2
```
Which all looks correct to me.

**Comment by wsfulton** [comment]
Possibly related to #828.

**Comment by micahdlamb** [comment]
I get the crash if I update your python code to this:

```python
from example import *
class MyDerived(Derived):
    def test(self, x=0):
        print("In MyDerived.test {}".format(x))
        super().test(x)
d = MyDerived()
Base.call_test(d)
```
