### ISSUE TITLE
enum array not work in python

### ISSUE THREAD

**Issue by Tysonliang** [swig/swig#2664]
it is my example
%include <std_array.i>

%inline %{
#include <array>
class TPC_ConsoleAct {
public:
  enum TPC_FDState : uint32_t
  {
    FD_STATE_UNKNOWN,
    FD_STATE_MACHINE
  };
  std::array<TPC_FDState, 2>& funcState()
  {
    return m_funcState;
  }
  std::array<TPC_FDState, 2> m_funcState;
};
%}

%template(Array_TPC_FDState_2) std::array<TPC_ConsoleAct::TPC_FDState, 2>;

At the python:
console = TPC_ConsoleAct1()
console.funcState([TPC_ConsoleAct1.FD_STATE_UNKNOWN,TPC_ConsoleAct1.FD_STATE_UNKNOWN])
it throw a erro "TypeError: Wrong number or type of arguments for overloaded function 'TPC_ConsoleAct1_funcState'.
  Possible C/C++ prototypes are:
    TPC_ConsoleAct1::funcState()
    TPC_ConsoleAct1::funcState(std::array< TPC_ConsoleAct1::TPC_FDState,2 >)"

**Comment by ojwb** [comment]
Your example doesn't match up: `TPC_ConsoleAct` in the interface file vs `TPC_ConsoleAct1` in the python to reproduce, but more confusingly you show an error when passing a python array to C/C++ but in the interface file the `funcState` method doesn't take a parameter, it instead returns a non-const reference to a `std::array` from C/C++ to python.

If the interface file represents your problem, then I suspect it's because you are returning a non-const reference and so SWIG returns a wrapped `std::array` - see the comment in `Lib/std/std_array.i`:

```
// ------------------------------------------------------------------------
// std::array
// 
// The aim of all that follows would be to integrate std::array with 
// as much as possible, namely, to allow the user to pass and 
// be returned tuples or lists.
// const declarations are used to guess the intent of the function being
// exported; therefore, the following rationale is applied:
// 
//   -- f(std::array<T, N>), f(const std::array<T, N>&):
//      the parameter being read-only, either a sequence or a
//      previously wrapped std::array<T, N> can be passed.
//   -- f(std::array<T, N>&), f(std::array<T, N>*):
//      the parameter may be modified; therefore, only a wrapped std::array
//      can be passed.
//   -- std::array<T, N> f(), const std::array<T, N>& f():
//      the array is returned by copy; therefore, a sequence of T:s 
//      is returned which is most easily used in other functions
//   -- std::array<T, N>& f(), std::array<T, N>* f():
//      the array is returned by reference; therefore, a wrapped std::array
//      is returned
//   -- const std::array<T, N>* f(), f(const std::array<T, N>*):
//      for consistency, they expect and return a plain array pointer.
// ------------------------------------------------------------------------
```

 If you want a wrapped Python sequence returned then return a const reference (or you can probably use `%apply` to tell SWIG to pretend you did if you can't modify the code being wrapped).

If that's not it, please provide a self-consistent reproducer.

**Comment by Tysonliang** [comment]
**.cxx file** 
void TPC_ConsoleStateAct::funcState(
        const std::array<TPC_ConsoleState, 2>& _funcState)
{
    m_funcState = _funcState;
}

const std::array<TPC_ConsoleState, 2>& TPC_ConsoleStateAct::funcState() const
{
    return m_funcState;
}

std::array<TPC_ConsoleState, 2>& TPC_ConsoleStateAct::funcState()
{
    return m_funcState;
}
**.i file**
%{
#include "tpc_console_state.h"
%}
//以下enum为自动添加
enum TPC_ConsoleState : uint32_t
{
    CONSOLE_STATE_UNKNOWN,
    CONSOLE_STATE_MACHINE
};
%ignore TPC_ConsoleStateAct::TPC_ConsoleStateAct(TPC_ConsoleStateAct&&);
%ignore TPC_ConsoleStateAct::funcState(std::array<TPC_ConsoleState, 2>&&);
%ignore TPC_ConsoleStateAct::funcState() const;
%template(TPC_ConsoleState_2_array) std::array<TPC_ConsoleState,2>;
%include "tpc_console_state.h"


**py file**
from topic_py.tpc_console_state import *
a = TPC_ConsoleStateAct()
a.funcState([CONSOLE_STATE_UNKNOWN,CONSOLE_STATE_UNKNOWN])

throw exception: 
 File "/workspaces/Anew/TestPlatform/Pyson/topic/test.py", line 3, in <module>
    a.funcState([CONSOLE_STATE_UNKNOWN,CONSOLE_STATE_UNKNOWN])
  File "/workspaces/Anew/TestPlatform/Pyson/topic/topic_py/tpc_console_state.py", line 215, in funcState
    return _tpc_console_stateWrapper.TPC_ConsoleStateAct_funcState(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'TPC_ConsoleStateAct_funcState'.
  Possible C/C++ prototypes are:
    TPC_ConsoleStateAct::funcState(std::array< TPC_ConsoleState,2 > const &)
    TPC_ConsoleStateAct::funcState()

**Comment by ojwb** [comment]
Can you show `tpc_console_state.h` too?

**Comment by Tysonliang** [comment]
**tpc_console_state.h**
```

enum TPC_ConsoleState : uint32_t
{
    CONSOLE_STATE_UNKNOWN,
    CONSOLE_STATE_MACHINE
};

class TPC_ConsoleStateAct
{
public:

    eProsima_user_DllExport TPC_ConsoleStateAct();

    eProsima_user_DllExport ~TPC_ConsoleStateAct();

    eProsima_user_DllExport TPC_ConsoleStateAct(
            const TPC_ConsoleStateAct& x);
    eProsima_user_DllExport TPC_ConsoleStateAct(
            TPC_ConsoleStateAct&& x);
    eProsima_user_DllExport TPC_ConsoleStateAct& operator =(
            const TPC_ConsoleStateAct& x);
    eProsima_user_DllExport TPC_ConsoleStateAct& operator =(
            TPC_ConsoleStateAct&& x)
    eProsima_user_DllExport bool operator ==(
            const TPC_ConsoleStateAct& x) const;
    eProsima_user_DllExport bool operator !=(
            const TPC_ConsoleStateAct& x) const;
    eProsima_user_DllExport void funcState(
            const std::array<TPC_ConsoleState, 2>& _funcState);
    eProsima_user_DllExport void funcState(
            std::array<TPC_ConsoleState, 2>&& _funcState);
    eProsima_user_DllExport const std::array<TPC_ConsoleState, 2>& funcState() const;
    eProsima_user_DllExport std::array<TPC_ConsoleState, 2>& funcState();

private:
    std::array<TPC_ConsoleState, 2> m_funcState;
};
```

**Comment by ojwb** [comment]
This is still not a complete self-contained example - there are numerous problems, e.g. a missing `;` here:
```
    eProsima_user_DllExport TPC_ConsoleStateAct& operator =(
            TPC_ConsoleStateAct&& x)
```

You don't include a header to define `uint32_t`.

`tpc_console_state.cxx` doesn't include the header so fails to compile.

There's no definition for the `TPC_ConsoleStateAct` constructors, desctructor and several other methods so linking the `.so` fails.

`eProsima_user_DllExport` isn't defined away for SWIG so it fails to parse the file.

You don't `#include <array>` so the resulting C++ code won't compile.

You don't `%include std_array.i` in the interface file so SWIG doesn't know about `std::array`.

Please actually test your reproducers in future, but this time I've fixed all the problems and stripped down to a more minimal reproducer:

tpc_console_state.i:

```
%module topic_py
%include std_array.i
%inline %{
#include <array>
enum E { A, B };
%}

%template(E2) std::array<E, 2>;

%inline %{
class T {
    std::array<E, 2> m;
public:
    T() {}
    void f(const std::array<E, 2>& _m) { m = _m; }
};
%}
```

Process with:

```
swig -python -c++ tpc_console_state.i
g++ `python3-config --cflags` -shared -fPIC tpc_console_state_wrap.cxx -o _topic_py.so
python3 runme.py
```

runme.py:

```
from topic_py import *
a = T()
a.f([A, B])
```

This fails with:

```
Traceback (most recent call last):
  File "/home/olly/git/swig/gh2664/runme.py", line 3, in <module>
    a.f([A, B])
  File "/home/olly/git/swig/gh2664/topic_py.py", line 203, in f
    return _topic_py.T_f(self, _m)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'T_f', argument 2 of type 'std::array< E,2 > const &'
```

I've already wasted more time than I really have right now just getting to this stage, but at least there's a complete reproducer now if someone wants to investigate further.

**Comment by richiware** [comment]
I was able to make work collections of enumerations. The problem is SWIG is not considering the enumeration as a primitive. I was able to make a workaround that considers enumeration as primitive.

My C++ example contains:
```cpp
enum Color : uint32_t
{
    RED,
    GREEN,
    BLUE,
    YELLOW,
    MAGENTA
};

// Later I have class's members and functions using next type.
std::array<Color, 3> array_of_enum;
```

My SWIG `.i` file contains:
```swig
// This define sets the type_traits of an enumeration as primitive.
%define %traits_penumn(Type...)
  %fragment(SWIG_Traits_frag(Type),"header",
        fragment="StdTraits") {
namespace swig {
  template <> struct traits< Type > {
    typedef value_category category;
    static const char* type_name() { return  #Type; }
  };
}
}
%enddef

// Use my enum as primitive
%traits_penumn(enum Color);

// Define my array in SWIG as an array of enums. It is important to write `enum` before the type (`Color`).
%template(Color_3_array) std::array<enum Color,3>;
```

This works for me.

**Comment by Tysonliang** [comment]
It worked！！！ thanks very much！
