### ISSUE TITLE
[python] import fails when using constants as default arguments

### ISSUE THREAD

**Issue by xantares** [swig/swig#296]
Hi,

I think there's another issue with the modification that landed in the 3.0.3 regarding how arguments are passed, other than the one fixed at #294.

Here's a MNWE from the problem I encountered in my lib:
```
class Foo
{
public:
  enum ExternalFileFormat { CSV };
  Foo(double x = 8.0);
private:
  double x_;
};

class Bar : public Foo
{
public:
  Bar(double x = 8.0, double y = 9.6);

  static Bar FromFile(const std::string & fileName,
      const std::string & parameters = "",
      const ExternalFileFormat format = CSV) {return Bar(9.7); }

private:
  double y_;
};
```

With the 3.0.3 or the PR #294 tip, it fails on import:
```
    def Bar_FromFile(fileName, parameters="", format=CSV):
NameError: name 'CSV' is not defined
```

because CSV is valid only in the Foo class scope:
```
class Foo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Foo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Foo, name)
    CSV = _example.Foo_CSV
```

and it fails at the (new) definition of Bar::FromFile:
```
def Bar_FromFile(fileName, parameters="", format=CSV):
    return _example.Bar_FromFile(fileName, parameters, format)
Bar_FromFile = _example.Bar_FromFile
```

with the following traceback:
```
Traceback (most recent call last):
  File "/home/xantares/projects/swig_test/python/main.py", line 1, in <module>
    import example
  File "/home/xantares/projects/swig_test/build/install/lib/python2.7/dist-packages/example.py", line 213, in <module>
    def Bar_FromFile(fileName, parameters="", format=CSV):
NameError: name 'CSV' is not defined
```

What do you think ?

**Comment by rwstoneback** [comment]
Just updated to 3.0.3 as well and I'm seeing this same issue. 
If I manually put the class name in their (ie. Foo.CSV), it works fine.
Seems like a bug to me.
