### ISSUE TITLE
SWIG 3.0.3 ignores 'U' digit's prefix in C++ default args 

### ISSUE THREAD

**Issue by HaK1R** [swig/swig#313]
When I generate Python wrapper for C++ interface it ignores 'U' in digit therefore the produced code fails with syntax error.

Interface:
```
class SBBroadcaster
{
public:
    SBBroadcaster ();

    SBBroadcaster (const char *name);

    SBBroadcaster (const SBBroadcaster &rhs);
    
    ~SBBroadcaster();

    bool
    IsValid () const;

    void
    Clear ();

    void
    BroadcastEventByType (uint32_t event_type, bool unique = false);
    
    void
    BroadcastEvent (const lldb::SBEvent &event, bool unique = false);

    void
    AddInitialEventsToListener (const lldb::SBListener &listener, uint32_t requested_events);
    
    uint32_t
    AddListener (const lldb::SBListener &listener, uint32_t event_mask);
    
    const char *
    GetName () const;
    
    bool
    EventTypeHasListeners (uint32_t event_type);

    bool
    RemoveListener (const lldb::SBListener &listener, uint32_t event_mask = UINT32_MAX);
```

Generated file (with error on line 1867):
```
 1852     def AddListener(self, listener, event_mask):
 1853         """AddListener(SBBroadcaster self, SBListener listener, uint32_t event_mask) -> uint32_t"""
 1854         return _lldb.SBBroadcaster_AddListener(self, listener, event_mask)
 1855 
 1856 
 1857     def GetName(self):
 1858         """GetName(SBBroadcaster self) -> str const *"""
 1859         return _lldb.SBBroadcaster_GetName(self)
 1860 
 1861 
 1862     def EventTypeHasListeners(self, event_type):
 1863         """EventTypeHasListeners(SBBroadcaster self, uint32_t event_type) -> bool"""
 1864         return _lldb.SBBroadcaster_EventTypeHasListeners(self, event_type)
 1865 
 1866 
 1867     def RemoveListener(self, listener, event_mask=4294967295U):
 1868         """
 1869         RemoveListener(SBBroadcaster self, SBListener listener, uint32_t event_mask=4294967295U) -> bool
 1870         RemoveListener(SBBroadcaster self, SBListener listener) -> bool
 1871         """
 1872         return _lldb.SBBroadcaster_RemoveListener(self, listener, event_mask)
```

Error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/IliaK/p/llvm/build_ninja/lib/python2.7/site-packages/lldb/__init__.py", line 1867
    def RemoveListener(self, listener, event_mask=4294967295U):
                                                            ^
SyntaxError: invalid syntax
```

BTW, if we remove 'U' by hand it'll solve this problem:
```
@@ -56,7 +56,7 @@ public:
     EventTypeHasListeners (uint32_t event_type);
 
     bool
-    RemoveListener (const lldb::SBListener &listener, uint32_t event_mask = UINT32_MAX);
+    RemoveListener (const lldb::SBListener &listener, uint32_t event_mask = 4294967295);
     
     bool
     operator == (const lldb::SBBroadcaster &rhs) const;
```

**Comment by ojwb** [comment]
This should already be fixed in 3.0.4:

```
2015-01-12: vadz
            [Python] Fix #294 #296 - Regression introduced in SWIG-3.0.3 when
            wrapping functions with default arguments. Invalid or missing default
            arguments were sometimes being generated into the python layer.
```

I can't easily test your case as it's incomplete - your "Interface" file is truncated, and you didn't specify the SWIG command line you used.  If you can reproduce this with 3.0.4, please reopen and include a complete interface file and command line.
