### ISSUE TITLE
Wrapper is generated with functions not defined in python for Linux

### ISSUE THREAD

**Issue by OlivierLeBozec** [swig/swig#351]
Hi folks,
I'm using Linux for raspberry pi version 2.7.
I want to bind a C++ code with python. So swig seems to be a solution.
But I encounter a error so maybe I've miss something.

pi@raspberrypi-3Ebis ~/Sources/depot01/simulator $ python Siimulator.py
Traceback (most recent call last):
  File "Siimulator.py", line 26, in <module>
    _Siimulator = swig_import_helper()
  File "Siimulator.py", line 22, in swig_import_helper
    _mod = imp.load_module('_Siimulator', fp, pathname, description)
ImportError: ./_Siimulator.so: undefined symbol: PyTuple_Check

Here is a subset of functions available in 2.7:
pi@raspberrypi-3Ebis /usr/lib/python2.7/config $ readelf -a libpython2.7.so | grep Tuple
002346f8  00044b15 R_ARM_GLOB_DAT    0025d8c0   PyTupleIter_Type
00234728  00017f15 R_ARM_GLOB_DAT    0025ee70   PyTuple_Type
   383: 0025ee70   196 OBJECT  GLOBAL DEFAULT   22 PyTuple_Type
   414: 00110910    56 FUNC    GLOBAL DEFAULT   12 PyTuple_Size
   432: 000e78b4   136 FUNC    GLOBAL DEFAULT   12 PyArg_VaParseTupleAndKeyw
   461: 0010bb84   520 FUNC    GLOBAL DEFAULT   12 PyArg_UnpackTuple
   859: 00110bd8   292 FUNC    GLOBAL DEFAULT   12 PyTuple_SetItem
   939: 0010d5a4   136 FUNC    GLOBAL DEFAULT   12 PyList_AsTuple
  1074: 00163d6c   416 FUNC    GLOBAL DEFAULT   12 PyTuple_New
  1076: 000e7830   132 FUNC    GLOBAL DEFAULT   12 _PyArg_VaParseTupleAndKey
  1079: 00110cfc   600 FUNC    GLOBAL DEFAULT   12 _PyTuple_Resize
  1099: 0025d8c0   196 OBJECT  GLOBAL DEFAULT   22 PyTupleIter_Type
  1243: 001423ac   148 FUNC    GLOBAL DEFAULT   12 _PyArg_ParseTupleAndKeywo
  1248: 000dfdf4    52 FUNC    GLOBAL DEFAULT   12 PyArg_ParseTuple
  1267: 00046f18    52 FUNC    GLOBAL DEFAULT   12 _PyArg_ParseTuple_SizeT
  1325: 00086fb8   536 FUNC    GLOBAL DEFAULT   12 PySequence_Tuple
  1328: 00110a68   132 FUNC    GLOBAL DEFAULT   12 PyTuple_GetItem
  1386: 0003d108   236 FUNC    GLOBAL DEFAULT   12 PyTuple_GetSlice
  1433: 00132490   120 FUNC    GLOBAL DEFAULT   12 _Py_Tuple
  1452: 0013e87c   112 FUNC    GLOBAL DEFAULT   12 PyTuple_ClearFreeList
  1468: 00142440   152 FUNC    GLOBAL DEFAULT   12 PyArg_ParseTupleAndKeywor
  1490: 00164cb4   116 FUNC    GLOBAL DEFAULT   12 PyTuple_Pack
  1524: 0013a198   228 FUNC    GLOBAL DEFAULT   12 _PyTuple_MaybeUntrack
  1548: 0013e8ec    96 FUNC    GLOBAL DEFAULT   12 PyTuple_Fini

Here is part of the code generated by the command "swig -python -c++ -v -o Siimulator_wrap.cpp Siimulator.i".
....
SWIGINTERN PyObject*
SWIG_Python_AppendOutput(PyObject* result, PyObject* obj) {
#if !defined(SWIG_PYTHON_OUTPUT_TUPLE)
  if (!result) {
    result = obj;
  } else if (result == Py_None) {
    Py_DECREF(result);
    result = obj;
  } else {
    if (!PyList_Check(result)) {
      PyObject *o2 = result;
      result = PyList_New(1);
      PyList_SetItem(result, 0, o2);
    }
    PyList_Append(result,obj);
    Py_DECREF(obj);
  }
  return result;
#else
  PyObject*   o2;
  PyObject*   o3;
  if (!result) {
    result = obj;
  } else if (result == Py_None) {
    Py_DECREF(result);
    result = obj;
  } else {
    if (!PyTuple_Check(result)) {
      o2 = result;
      result = PyTuple_New(1);
      PyTuple_SET_ITEM(result, 0, o2);
    }
    o3 = PyTuple_New(1);
    PyTuple_SET_ITEM(o3, 0, obj);
    o2 = result;
    result = PySequence_Concat(o2, o3);
    Py_DECREF(o2);
    Py_DECREF(o3);
  }
  return result;
#endif
}

As you can see PyTuple_Check() is used. But this function is NOT available in Python lib 2.6 neither in 2.8, 3 and 3.2. Under ubuntu 14.04 and raspbian either.
I've check using swig 2.0 and swig 3.0.4 same issue. 

Here is the list of ALL missing functions in the wrapper :
Siimulator_wrap.o: In function `SWIG_Python_AppendOutput':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:1280: undefined reference to `PyList_Check'
Siimulator_wrap.o: In function `SWIG_Python_UnpackTuple':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:1328: undefined reference to `PyTuple_Check'
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:1340: undefined reference to `PyTuple_GET_SIZE'
Siimulator_wrap.o: In function `SwigPyClientData_New':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:1473: undefined reference to `PyClass_Check'
Siimulator_wrap.o: In function `SwigPyObject_dealloc':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:1722: undefined reference to `PyObject_Del'
Siimulator_wrap.o: In function `SwigPyPacked_dealloc':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:2078: undefined reference to `PyObject_Del'
Siimulator_wrap.o: In function `SwigPyPacked_New':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:2179: undefined reference to `PyObject_Del'
Siimulator_wrap.o: In function `SWIG_Python_GetSwigThis':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:2249: undefined reference to `PyInstance_Check'
Siimulator_wrap.o: In function `SWIG_Python_ConvertFunctionPtr':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:2406: undefined reference to `PyCFunction_Check'
Siimulator_wrap.o: In function `SWIG_Python_SetModule':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:2721: undefined reference to `_Py_InitPyPyModule'
Siimulator_wrap.o: In function `SWIG_AsVal_double':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:3075: undefined reference to `PyFloat_Check'
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:3078: undefined reference to `PyInt_Check'
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:3081: undefined reference to `PyLong_Check'
Siimulator_wrap.o: In function `SWIG_AsVal_long':
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:3154: undefined reference to `PyInt_Check'
/home/SII/olebozec/LocalData/depot01/simulator/Siimulator_wrap.cpp:3157: undefined reference to `PyLong_Check'

**Comment by OlivierLeBozec** [comment]
Hi,
My bad. PyTuple_Check() and others are macro an not functions.
It was defined twice in my env in different way. It can be closed.
Olivier.
