### ISSUE TITLE
Problem with latin characters

### ISSUE THREAD

**Issue by AdamGerthel** [swig/swig#554]
I have a datasource that uses Swedish characters in keys/properties in JSON, such as
```
data: [
  {
    Benämning: "example text",
    Antal: 2,
    Ordernr: 123456,
    Ändrad: 1
  }
]
```

But that seems to cause issues. Some data is not being printed at all even though it's there, and for some keys I'm getting this error:

````
Error: SyntaxError: Unexpected token !== in file <path-to-project>/views/index.html.
    at Object.exports.throwError (<path-to-project>/node_modules/swig/lib/utils.js:183:9)
    at precompile (<path-to-project>/node_modules/swig/lib/swig.js:505:13)
    at compile (<path-to-project>/node_modules/swig/lib/swig.js:606:16)
    at <path-to-project>/node_modules/swig/lib/swig.js:684:27
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)
```

The template file is very simple:

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Ej beställda orderrader.</title>
</head>
<body>
  <table>
    {% for row in data %}
      <tr>
        <td>{{ row.Ordernr }}</td>
        <td>{{ row.Benämning }}</td>
        <td>{{ row.Antal }}</td>
        <td>{{ row.Ändrad }}</td>
      </tr>
    {% endfor %}
  </table>
</body>
</html>
```
Any ideas on that the problem could be? It only happens to the properties that have latin characters in their keys.

**Comment by ojwb** [comment]
You have the wrong SWIG project - this one is: http://swig.org/

**Comment by AdamGerthel** [comment]
Woops! :)
