### ISSUE TITLE
Ruby %shared_ptr behavior inconsistency

### ISSUE THREAD

**Issue by tjensen** [swig/swig#590]
I have observed some `%shared_ptr` behavior in Ruby that I believe is incorrect. Consider the following hpp and cpp files

```cpp
// Blob.hpp
#include <memory>
#include <vector>
#include <string>

struct Foo {
    typedef std::shared_ptr<Foo> Ptr;
    std::string name() const;
};

class Bar {
    public:
        Bar();
        Foo::Ptr foo() const;
        Foo * rfoo() const;
        std::vector<Foo::Ptr> foos() const;
        std::vector<Foo *> rfoos() const;
    private:
        std::vector<Foo::Ptr> m_foos;
};
```

```cpp
// Blob.cpp
#include <memory>
#include <vector>
#include <string>
#include <algorithm>

#include "Blob.hpp"

std::string Foo::name() const {
    return "Foo";
}

Bar::Bar() {
    for ( auto i = 0; i < 100; ++i ) {
        m_foos.push_back( std::make_shared<Foo>() );
    }
}

Foo::Ptr Bar::foo() const {
    return m_foos.front();
}

Foo * Bar::rfoo() const {
    return m_foos.front().get();
}

std::vector<Foo::Ptr> Bar::foos() const {
    return m_foos;
}

std::vector<Foo *> Bar::rfoos() const {
    std::vector<Foo *> result( m_foos.size() );
    std::transform( m_foos.begin(), m_foos.end(), result.begin(),
            []( Foo::Ptr foo ) { return foo.get(); } );
    return result;
}
```

Here is the SWIG .i file I am using with the above code:

```
%module Blob

%include <std_shared_ptr.i>
%include <std_vector.i>
%include <std_string.i>

%{ #include "Blob.hpp" %}

%shared_ptr(Foo);

%template (FooVector) std::vector<std::shared_ptr<Foo>>;
%template (FooRawVector) std::vector<Foo *>;

%include "Blob.hpp"
```

When I call `Bar#rfoo` from Ruby, SWIG automatically wraps the returned raw pointer in a shared_ptr, effectively making `Bar#rfoo` and `Bar#foo` equivalent.

However, when I call `Bar#rfoos` from Ruby, SWIG does not automatically wrap the raw pointers contained in the returned vector. I expected that the raw pointers would be wrapped in shared_ptrs, thereby making `Bar#rfoos` effectively equivalent to `Bar#foos`.

The following Ruby tests exhibit the unexpected behavior:

```ruby
require_relative 'Blob'
require 'minitest/autorun'

class BlobTest < MiniTest::Unit::TestCase
  attr_reader :bar
  def setup
    @bar = Blob::Bar.new
  end
  def test_types
    assert_equal( Blob::Foo, bar.foo.class )
    assert_equal( Blob::Foo, bar.rfoo.class )
    assert_equal( Array, bar.foos.class )
    assert_equal( Blob::Foo, bar.foos.first.class )
    assert_equal( Array, bar.rfoos.class )
    assert_equal( Blob::Foo, bar.rfoos.first.class )  # fails
  end
  def test_names
    assert_equal( 'Foo', bar.foo.name )
    assert_equal( 'Foo', bar.rfoo.name )
    assert_equal( 'Foo', bar.foos.first.name )
    assert_equal( 'Foo', bar.rfoos.first.name )  # error
  end
end
```

When I run the above tests, the assertion annotated with `# fails` expects `Blob::Foo` but actually gets `SWIG::TYPE_p_Foo` and the assertion annotated with `# error` reports the error, `NoMethodError: undefined method `name' for #<SWIG::TYPE_p_Foo:0x00000001387420>`.

For now, I can work around the issue using `%ignore` and `%extend`.

Thank you so much for adding `%shared_ptr` support for Ruby! It has already helped me greatly!

**Comment by tjensen** [comment]
This issue is not specific to Ruby. The following Python tests exhibit the same behavior:

```python
import Blob
import unittest

class TestBlob(unittest.TestCase):

  def setUp(self):
    self.bar = Blob.Bar()

  def test_types(self):
    self.assertEqual( Blob.Foo, type(self.bar.foo()) )
    self.assertEqual( Blob.Foo, type(self.bar.rfoo()) )
    self.assertEqual( tuple, type(self.bar.foos()) )
    self.assertEqual( Blob.Foo, type(self.bar.foos()[0]) )
    self.assertEqual( tuple, type(self.bar.rfoos()) )
    self.assertEqual( Blob.Foo, type(self.bar.rfoos()[0]) )  # fails

  def test_names(self):
    self.assertEqual( 'Foo', self.bar.foo().name() )
    self.assertEqual( 'Foo', self.bar.rfoo().name() )
    self.assertEqual( 'Foo', self.bar.foos()[0].name() )
    self.assertEqual( 'Foo', self.bar.rfoos()[0].name() )  # error

if __name__ == '__main__':
    unittest.main()
```

Test output:

```
======================================================================
ERROR: test_names (__main__.TestBlob)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "blob.py", line 21, in test_names
    self.assertEqual( 'Foo', self.bar.rfoos()[0].name() )  # error
AttributeError: 'SwigPyObject' object has no attribute 'name'

======================================================================
FAIL: test_types (__main__.TestBlob)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "blob.py", line 15, in test_types
    self.assertEqual( Blob.Foo, type(self.bar.rfoos()[0]) )  # fails
AssertionError: <class 'Blob.Foo'> != <type 'SwigPyObject'>

----------------------------------------------------------------------
```
