### ISSUE TITLE
Problems with vector of shared_ptr<const X> in Python

### ISSUE THREAD

**Issue by Richard-Gmac** [swig/swig#753]
I'm using SWIG to add a Python wrapper to a large existing C++ library. The library contains many std::shared_ptr to a const type and these are used extensively in containers. There seems to be a problem mapping vectors of such pointers into Python. I'm using the following SWIG file:

```
%module py

%include <std_shared_ptr.i>
%include <std_vector.i>

%{
#include <memory>
#include <vector>
using std::shared_ptr;
using std::make_shared;

struct DoubleValue {
        double value;
        DoubleValue();
        DoubleValue(double v);
};

typedef shared_ptr<DoubleValue> DoubleValuePtr;
typedef shared_ptr<const DoubleValue> ConstDoubleValuePtr;

double sumIVP(const std::vector<DoubleValuePtr>& is);
double sumConstIVP(const std::vector<ConstDoubleValuePtr>& is);
std::vector<DoubleValuePtr> toDV(const std::vector<double>& vs);
std::vector<ConstDoubleValuePtr> toConstDV(const std::vector<double>& vs);
%}

%shared_ptr(DoubleValue)

struct DoubleValue {
        double value;
        DoubleValue();
        DoubleValue(double v);
};

%typedef shared_ptr<DoubleValue> DoubleValuePtr;
%typedef shared_ptr<const DoubleValue> ConstDoubleValuePtr;

%template(DoubleVector) std::vector<double>;
%template(DoubleValuePtrVector) std::vector<DoubleValuePtr>;
%template(ConstDoubleValuePtrVector) std::vector<ConstDoubleValuePtr>;

%inline %{

DoubleValue::DoubleValue() : value(0){}

DoubleValue::DoubleValue(double v)
    : value(v)
{
}

double sumDV(const std::vector<DoubleValuePtr>& is)
{
    double s = 0;
    for(auto i : is)
    {
        s += i->value;
    }
    return s;
}

double sumConstDV(const std::vector<ConstDoubleValuePtr>& is)
{
    double s = 0;
    for(auto i : is)
    {
        s += i->value;
    }
    return s;
}

std::vector<DoubleValuePtr> toDV(const std::vector<double>& vs)
{
    std::vector<DoubleValuePtr> vec;
    for(auto x : vs)
    {
        vec.push_back(std::make_shared<DoubleValue>(x));
    }
    return vec;
}

std::vector<ConstDoubleValuePtr> toConstDV(const std::vector<double>& vs)
{
    std::vector<ConstDoubleValuePtr> vec;
    for(auto x : vs)
    {
        vec.push_back(std::make_shared<DoubleValue>(x));
    }
    return vec;
}

%}
```

Building it on Windows/Visual Studio 12 using:
`swig.exe  -python -outdir . -c++ -IC:/Python27/include -o wrap.cxx py.i`
`cl /Debug /EHsc -IC:/Python27/include -c wrap.cxx`
`link /out:_py.pyd /dll wrap.obj c:/Python27/libs/python27.lib /Debug`

And driving it with this Python script:

```
import py

dv = py.toDV([1,2,3])
constdv = py.toConstDV([1,2,3])

print "Type dv[0]: %s" % type(dv[0])    #  <class 'py.DoubleValue'>
print "Value dv[0]: %d" % dv[0].value   # 1

print "Type constdv[0]: %s" % type(constdv[0])   # <type 'SwigPyObject'>
#print "Value constdv[0]: %d" % constdv[0].value   # AttributeError: 'SwigPyObject' object has no attribute 'value'

print "Sum = %d" % py.sumDV(dv)
print "Sum = %d" % py.sumConstDV(dv)
#print "Sum = %d" % py.sumDV(constdv)   # Segfault
print "Sum = %d" % py.sumConstDV(constdv)
```

It's not really practical to work around using %extend/%ignore due to the size of the library.

**Comment by okainov** [comment]
Seems there is still an issue with that, is there any updates here?

**Comment by ojwb** [comment]
It still seems to be present in git master.

Had to tweak the example a bit for Python3 and Linux.  Here's the updated `test.py`:

```
import py

dv = py.toDV([1,2,3])
constdv = py.toConstDV([1,2,3])

print("Type dv[0]: %s" % type(dv[0]))   #  <class 'py.DoubleValue'>
print("Value dv[0]: %d" % dv[0].value)  # 1

print("Type constdv[0]: %s" % type(constdv[0]))  # <type 'SwigPyObject'>
#print("Value constdv[0]: %d" % constdv[0].value)  # AttributeError: 'SwigPyObject' object has no attribute 'value'

print("Sum = %d" % py.sumDV(dv))
print("Sum = %d" % py.sumConstDV(dv))
#print("Sum = %d" % py.sumDV(constdv))  # Segfault
print("Sum = %d" % py.sumConstDV(constdv))
```

Built and run with:

```
$ swig -python -c++ py.i
$ g++ `python3-config --cflags` py_wrap.cxx -fPIC -shared -o _py.so
$ python3 test.py
Type dv[0]: <class 'py.DoubleValue'>
Value dv[0]: 1
Type constdv[0]: <class 'SwigPyObject'>
Sum = 6
Traceback (most recent call last):
  File "/home/olly/git/swig/gh753/test.py", line 13, in <module>
    print("Sum = %d" % py.sumConstDV(dv))
  File "/home/olly/git/swig/gh753/py.py", line 461, in sumConstDV
    return _py.sumConstDV(_is)
TypeError: in method 'sumConstDV', argument 1 of type 'std::vector< ConstDoubleValuePtr,std::allocator< ConstDoubleValuePtr > > const &'
swig/python detected a memory leak of type 'unknown', no destructor found.
swig/python detected a memory leak of type 'unknown', no destructor found.
swig/python detected a memory leak of type 'unknown', no destructor found.
```

I don't really understand the shared_ptr wrapping machinery so this is probably one for someone else to investigate.

**Comment by ojwb** [comment]
I've closed https://sourceforge.net/p/swig/bugs/1231/ as a duplicate of this.  Also comes with a reproducer so would be good to confirm that is fixed when this is.

**Comment by emmenlau** [comment]
I think I'm affected by a similar, if not the same problem. My use case is with C# and `std::shared_ptr<const T>`. I have found that swig will happily allow both `std::shared_ptr<T>` and `std::shared_ptr<const T>` to be used in C#. This is problematic because it casts away the const, and makes const objects modifiable.

Is there some way to generally forbid `std::shared_ptr<const T>`?

**Comment by ojwb** [comment]
I think that's as documented here: https://www.swig.org/Doc4.2/SWIGPlus.html#SWIGPlus_const

At least for the dynamically-typed languages, the argument is essentially that trying to wrap `const`-correctly probably creates more problems than it solves.  For statically typed languages which have the concept of `const` that doesn't seem valid, but I guess they have inherited this pre-existing approach to `const`.

You could probably also provide typemaps for `std::shared_ptr<const MyType>` which expand to a `#error` - SWIG's type system knows about `const`, so I think it should pick the `const` typemaps only when it has to, and then you'd get a compile-time error.

**Comment by emmenlau** [comment]
Thanks a lot @ojwb , your suggestion is exactly correct.

I did first experiment with typemaps in my own interface files. They do solve the problem, however I am under the impression that I need to define such a typemap for every type `T` that is to be used in `std::shared_ptr<T>`. That again seemed error-prone to me, because it requires the developer to actively forbid types.

I could not find a way to write a catch-all-typemap. A regular expression like `%typemap(out) std::shared_ptr<const .*>` did not work.

With some searching, I found that I can moderately cleanly implement this in swig itself. I added the following patch:
```
From b35b1eb83d109a48febfecaa52d47f9262f5c704 Mon Sep 17 00:00:00 2001
From: Mario Emmenlauer <memmenlauer@biodataanalysis.de>
Date: Wed, 24 Jan 2024 11:06:57 +0100
Subject: Lib/csharp/boost_shared_ptr.i: Forbid the use of
 std::shared_ptr<const T> as a return type


diff --git a/Lib/csharp/boost_shared_ptr.i b/Lib/csharp/boost_shared_ptr.i
index d47fab558..ef4e7a1c3 100644
--- a/Lib/csharp/boost_shared_ptr.i
+++ b/Lib/csharp/boost_shared_ptr.i
@@ -155,6 +155,29 @@
 %}
 
 
+
+#if defined(SWIG_FORBID_CONST_SHARED_PTR)
+// Forbid the use of std::shared_ptr<const T> as a return type, since const is
+// not supported natively by C#. Otherwise const objects become modifiable.
+%typemap(out) const TYPE %{
+#error The return type std::shared_ptr<const $1_type> of method $symname() is not supported in the target language
+%}
+
+%typemap(out) SWIG_SHARED_PTR_QNAMESPACE::shared_ptr< const TYPE > %{
+#error The return type std::shared_ptr<const $1_type> of method $symname() is not supported in the target language
+%}
+
+%typemap(out) SWIG_SHARED_PTR_QNAMESPACE::shared_ptr< const TYPE > & %{
+#error The return type std::shared_ptr<const $1_type> of method $symname() is not supported in the target language
+%}
+
+%typemap(out) SWIG_SHARED_PTR_QNAMESPACE::shared_ptr< CONST TYPE > *& %{
+#error The return type std::shared_ptr<const $1_type> of method $symname() is not supported in the target language
+%}
+#endif
+
+
+
 %typemap (ctype)  SWIG_SHARED_PTR_QNAMESPACE::shared_ptr< CONST TYPE >,
                   SWIG_SHARED_PTR_QNAMESPACE::shared_ptr< CONST TYPE > &,
                   SWIG_SHARED_PTR_QNAMESPACE::shared_ptr< CONST TYPE > *,
```

With this patch in place, users can define `SWIG_FORBID_CONST_SHARED_PTR` in their interface file before including `std_shared_ptr.i`, and this will forbid any return values of type `std::shared_ptr<const T>` with a nice and helpful error message.

Is that a good way to do it? Would that be helpful to other users, i.e. to include it in swig?

**Comment by ojwb** [comment]
> A regular expression like `%typemap(out) std::shared_ptr<const .*>` did not work.

SWIG doesn't support regexps for types like that.

`SWIGTYPE` works as a catch-all type by itself.  Not sure if it'll work here, but maybe try `%typemap(out) std::shared_ptr<const SWIGTYPE>` and see if that works?

I don't know about your patch - you probably want @wsfulton for shared_ptr stuff.
