### ISSUE TITLE
Warnings with -Xcheck:jni

### ISSUE THREAD

**Issue by ojwb** [swig/swig#857]
Running the testsuite with `-Xcheck:jni` like this:

```
make check-java-test-suite JAVAFLAGS=-Xcheck:jni
```

gives a **lot** of warnings - here's a small sample:

```
checking java testcase java_director (with run test)
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethodV
	at java_director.java_directorJNI.delete_QuuxContainer(Native Method)
	at java_director.QuuxContainer.delete(QuuxContainer.java:33)
	- locked <0x00000005cae45148> (a java_director.QuuxContainer)
	at java_director.QuuxContainer.finalize(QuuxContainer.java:26)
	at java.lang.System$2.invokeFinalize(System.java:1270)
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethodV
	at java_director.java_directorJNI.delete_QuuxContainer(Native Method)
	at java_director.QuuxContainer.delete(QuuxContainer.java:33)
	- locked <0x00000005cae45148> (a java_director.QuuxContainer)
	at java_director.QuuxContainer.finalize(QuuxContainer.java:26)
	at java.lang.System$2.invokeFinalize(System.java:1270)
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethodV
	at java_director.java_directorJNI.delete_QuuxContainer(Native Method)
	at java_director.QuuxContainer.delete(QuuxContainer.java:33)
	- locked <0x00000005cae45148> (a java_director.QuuxContainer)
	at java_director.QuuxContainer.finalize(QuuxContainer.java:26)
	at java.lang.System$2.invokeFinalize(System.java:1270)
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticVoidMethod
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
	- locked <0x0000000719205630> (a java.lang.Object)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	- locked <0x00000007192055b8> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java_director_runme.WaitForGC(java_director_runme.java:21)
	at java_director_runme.main(java_director_runme.java:48)
```

Not sure if these could be false positives, but even if they are it would be nice to be able to suppress these if feasible so that `-Xcheck:jni` can be used to find actual issues (both with code in SWIG and with JNI code in user typemaps).

**Comment by wsfulton** [comment]
We used to run the test-suite with `-Xcheck:jni", but in Java 8 a ton of false positives were introduced so I turned them off in 57f1c378b2d785dbdd0275f11c3468ec5391ae99. This is unfortunate because when this option worked, it was very useful. We could use jdk-1.7 or (earlier versions around jdk-1.8.20 I think were okay) with this flag in our Travis testing or maybe 1.9 has got better, I havn't tried.

**Comment by ojwb** [comment]
The above was with "1.8.0_111".

I tried openjdk 9 from Debian experimental (`javac -version` reports `javac 9-Debian`; package version is 9~b149-1 - I guess this is probably a pre-release version) and that also gives a similar looking slew of warnings (I didn't try to compare in detail).

**Comment by DemiMarie** [comment]
@wsfulton Why do you believe that these warnings are false?  Remember that the JVM can throw a `java.lang.VirtualMachineError` (or any subclass thereof) *at any time*, so exceptions from *every* method need to be checked, even if the method is empty.

**Comment by wsfulton** [comment]
I couldn't make the warnings go away no matter what I tried. Am more than happy to consider patches to fix these warnings though.

**Comment by ojwb** [comment]
I just checked and I still get them with current SWIG git master and Java `openjdk version "11.0.13" 2021-10-19`.
