### ISSUE TITLE
Segfault with deprecated typemap language name

### ISSUE THREAD

**Issue by adeason** [swig/swig#891]
I have an old swig file that uses the old "lang name in typemap" feature, which apparently segfaults new versions of swig (tested against dee6b075, but it also happens with some other 3.0.x versions). Here is a simple example, as a test case in the test suite (I didn't submit a pull request, since I'm not really sure how to _fix_ it):

`Examples/test-suite/errors/swig_typemap_lang.i`:
```
%module xxx

%typemap(in, numinputs=1, python) int ""

void func(int arg);
```

`Examples/test-suite/errors/swig_typemap_lang.stderr`:
```
swig_typemap_lang.i:3: Warning 124: Specifying the language name in %typemap is deprecated - use #ifdef SWIG<LANG> instead.
```

Here is the stack strace of the segfault, when running that example:

```
(gdb) where
#0  __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
#1  0x000055555569f5a5 in typemap_replace_vars (s=s@entry=0x0, locals=locals@entry=0x0, type=0x7ffff6a22ab0, rtype=rtype@entry=0x7ffff6a22ab0, pname=pname@entry=0x7ffff6a22ad0, 
    lname=lname@entry=0x7ffff6a84ab0, index=1) at Swig/typemap.c:934
#2  0x00005555556a178a in typemap_attach_kwargs (nmatch=1, firstp=0x7ffff6a22a70, tmap_method=0x5555556b253f, tm=0x7ffff6a42ed0) at Swig/typemap.c:1560
#3  Swig_typemap_attach_parms (tmap_method=tmap_method@entry=0x5555556b253f, parms=parms@entry=0x7ffff6a22a70, f=f@entry=0x555555f11900) at Swig/typemap.c:1787
#4  0x00005555555c1bb6 in emit_attach_parmmaps (l=0x7ffff6a22a70, f=0x555555f11900) at Modules/emit.cxx:105
#5  0x000055555564f98a in PYTHON::functionWrapper (this=0x55555591e930, n=0x7ffff6a22b30) at Modules/python.cxx:2726
#6  0x00005555555f8a24 in Language::globalfunctionHandler (this=0x55555591e930, n=0x7ffff6a22b30) at Modules/lang.cxx:1155
#7  0x00005555555fc428 in Language::functionHandler (this=0x55555591e930, n=0x7ffff6a22b30) at Modules/lang.cxx:1077
#8  0x00005555555ffdad in Language::cDeclaration (this=0x55555591e930, n=0x7ffff6a22b30) at Modules/lang.cxx:1013
#9  0x00005555555f76d0 in Dispatcher::emit_one (this=this@entry=0x55555591e930, n=n@entry=0x7ffff6a22b30) at Modules/lang.cxx:119
#10 0x00005555555fa1e3 in Language::emit_one (this=0x55555591e930, n=0x7ffff6a22b30) at Modules/lang.cxx:399
#11 0x00005555555f799d in Dispatcher::emit_children (this=0x55555591e930, n=<optimized out>) at Modules/lang.cxx:211
#12 0x00005555555f71aa in Language::includeDirective (this=<optimized out>, n=<optimized out>) at Modules/lang.cxx:649
#13 0x00005555555f78ea in Dispatcher::emit_one (this=this@entry=0x55555591e930, n=n@entry=0x7ffff6a22610) at Modules/lang.cxx:165
#14 0x00005555555fa1e3 in Language::emit_one (this=0x55555591e930, n=0x7ffff6a22610) at Modules/lang.cxx:399
#15 0x00005555555f799d in Dispatcher::emit_children (this=0x55555591e930, n=<optimized out>) at Modules/lang.cxx:211
#16 0x00005555556582a5 in PYTHON::top (this=0x55555591e930, n=0x7ffff7f4aa50) at Modules/python.cxx:1016
#17 0x000055555560ac7a in SWIG_main (argc=<optimized out>, argv=<optimized out>, l=<optimized out>) at Modules/main.cxx:1303
#18 0x000055555556cc52 in main (margc=<optimized out>, margv=<optimized out>) at Modules/swigmain.cxx:207

```

The segfault occurs under typemap_attach_kwargs, because 'value' is NULL, since the relevant argument ('python') is not a name/value pair. I think `Source/CParse/parser.y` is supposed to catch the deprecated typemap lang and fix it here:

```
typemap_type   : kwargs {
                 Hash *p;
                 String *name;
                 p = nextSibling($1);
                 if (p && (!Getattr(p,"value"))) {
                   /* this is the deprecated two argument typemap form */
                   Swig_warning(WARN_DEPRECATED_TYPEMAP_LANG,cparse_file, cparse_line,
                                "Specifying the language name in %%typemap is deprecated - use #ifdef SWIG<LANG> instead.\n");
                   /* two argument typemap form */
                   name = Getattr($1,"name");
                   if (!name || (Strcmp(name,typemap_lang))) {
                     $$.method = 0;
                     $$.kwargs = 0;
                   } else {
                     $$.method = Getattr(p,"name");
                     $$.kwargs = nextSibling(p);
                   }
                 } else {
                   /* one-argument typemap-form */
                   $$.method = Getattr($1,"name");
                   $$.kwargs = p;
                 }
                }
               ;
```

But that only looks at the first 2 parameters to %typemap, and so it doesn't catch it if the lang name is after that (which it is, in the provided example). I thought I could change this to loop on nextSibling, checking all of the arguments, but I'm not exactly sure how to check if a "name" is a valid method, or if it looks like an old-style language name. (The above existing code assumes if we have 2 elements with no values, the first is the lang name.)

I am not arguing that the provided example is correct typemap syntax, but it did work with older versions of swig. As just a user of swig, I'm not sure if I care if this _works_, but segfaulting is quite rude. But the existing code tries to make it actually work, so I didn't want to break that, and making it actually work is a little beyond a swig novice like me. So, since I'm not sure, I'm submitting this as an issue instead of a PR.

**Comment by wsfulton** [comment]
Yes, let's move on and implement this deprecation with your new error message if there is no value provided. Yes, let's combine your new error message and the old one for the 2nd parameter. Might also be worth checking that the 1st parameter does not have a value assigned. The following ought to error out:
```swig
%typemap(argout=123) char * ""
```

**Comment by ojwb** [comment]
So it should.  Will implement all the above.
