### ISSUE TITLE
assignment of element of std::vector in python fails

### ISSUE THREAD

**Issue by ROTA-tor** [swig/swig#952]
If I use a std::vector (with c++11 enabled). The swig file looks like this:
```
%include <std_shared_ptr.i>
%shared_ptr(std::vector<std::string>)
%template(StringVector) std::vector<std::string>;
```
I  wrap this to python. In python I cannot assign to the vector. The following example fails
```
>>> import test
>>> str = test.StringVector()
>>> str.append('foo')     
>>> str[0] = "bar"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/$USER/path/test.py", line 678, in __setitem__
    return _test.StringVector___setitem__(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'StringVector___setitem__'.
  Possible C/C++ prototypes are:
    std::vector< std::string >::__setitem__(PySliceObject *,std::vector< std::string,std::allocator< std::string > > const &)
    std::vector< std::string >::__setitem__(PySliceObject *)
    std::vector< std::string >::__setitem__(std::vector< std::string >::difference_type,std::vector< std::string >::value_type const &)
```
This problem exists also for a vector of a self implemented class (e.g. `std::vector<MyClass>`)

I can fix this problem in the generated text.cxx. I have to apply the following change (please look for the comments):
```
SWIGINTERN PyObject *_wrap_StringVector___setitem__(PyObject *self, PyObject *args) {
  Py_ssize_t argc;
  PyObject *argv[4] = {
    0
  };
  Py_ssize_t ii;

  if (!PyTuple_Check(args)) SWIG_fail;
  argc = args ? PyObject_Length(args) : 0;
  for (ii = 0; (ii < 3) && (ii < argc); ii++) {
    argv[ii] = PyTuple_GET_ITEM(args,ii);
  }
  if (argc == 2) {
    int _v;
    int res = swig::asptr(argv[0], (std::vector< std::string,std::allocator< std::string > >**)(0));
    _v = SWIG_CheckState(res);
    if (_v) {
      {
        _v = PySlice_Check(argv[1]);
      }
      if (_v) {
        return _wrap_StringVector___setitem____SWIG_1(self, args);
      }
    }
  }
  if (argc == 3) {
    int _v;
    int res = swig::asptr(argv[0], (std::vector< std::string,std::allocator< std::string > >**)(0));
    _v = SWIG_CheckState(res);
    if (_v) {
      {
        _v = PySlice_Check(argv[1]);
      }
      if (_v) {
        int res = swig::asptr(argv[2], (std::vector< std::string,std::allocator< std::string > >**)(0));
        _v = SWIG_CheckState(res);
        if (_v) {
          return _wrap_StringVector___setitem____SWIG_0(self, args);
        }
      }
    }
  }
  if (argc == 3) {
    int _v;
    //
    // the following line is wrong
    // int res = swig::asptr(argv[0], (std::vector< std::string,std::allocator< std::string > >**)(0));
    // and must be replaced by this line
    int res = SWIG_ConvertPtr(argv[0], 0, SWIGTYPE_p_std__shared_ptrT_std__vectorT_std__string_std__allocatorT_std__string_t_t_t, 0); // <<== correct line
    _v = SWIG_CheckState(res);
    if (_v) {
      {
        int res = SWIG_AsVal_ptrdiff_t(argv[1], NULL);
        _v = SWIG_CheckState(res);
      }
      if (_v) {
        int res = SWIG_AsPtr_std_string(argv[2], (std::string**)(0));
        _v = SWIG_CheckState(res);
        if (_v) {
          return _wrap_StringVector___setitem____SWIG_2(self, args);
        }
      }
    }
  }

fail:
  SWIG_SetErrorMsg(PyExc_NotImplementedError,"Wrong number or type of arguments for overloaded function 'StringVector___setitem__'.\n"
    "  Possible C/C++ prototypes are:\n"
    "    std::vector< std::string >::__setitem__(PySliceObject *,std::vector< std::string,std::allocator< std::string > > const &)\n"
    "    std::vector< std::string >::__setitem__(PySliceObject *)\n"
    "    std::vector< std::string >::__setitem__(std::vector< std::string >::difference_type,std::vector< std::string >::value_type const &)\n");
  return 0;
}
```
I am using swig 3.0.12 and this problem occurs under Ubuntu and Windows.

**Comment by tamuratak** [comment]
Hi,
it would be appropriate to use `%shared_ptr(StringVector)` instead of `%shared_ptr(std::vector<std::string>)` here. Please try;

```
%include <std_shared_ptr.i>
%include <std_vector.i>
%include <std_string.i>

%shared_ptr(StringVector)
%template(StringVector) std::vector<std::string>;
```

Regards.

**Comment by wsfulton** [comment]
```swig
%{
#include <memory>
%}
%include <std_string.i>
%include <std_vector.i>
%include <std_shared_ptr.i>
%shared_ptr(std::vector<std::string>)
%template(StringVector) std::vector<std::string>;
```
The above works for me using latest master.

**Comment by tamuratak** [comment]
Hi,
this issue still exists for ruby. So it might do so for python.
Please run python code to check.

```sh
$ cat test.i 
%module test
%{
#include <memory>
%}
%include <std_vector.i>
%include <std_string.i>
%include <std_shared_ptr.i>
%shared_ptr(std::vector<std::string>)
%template(StringVector) std::vector<std::string>;

$ swig -ruby -c++ test.i
$ clang++ -I /opt/local/include/ruby-2.4.0/ -I /opt/local/include/ruby-2.4.0/x86_64-darwin16  -shared -o test.bundle test_wrap.cxx -L /opt/local/lib -l ruby2.4
$ cat t.rb 
require "./test"
include Test
a = StringVector.new(1)
a[0] = "abc"

$ ruby2.4 t.rb                                                                                                                                                 
t.rb:4:in `[]=': Wrong arguments for overloaded method '__setitem__'. (ArgumentError)
Possible C/C++ prototypes are:
    VALUE __setitem__(std::vector< std::string >::difference_type i, std::vector< std::string >::value_type const &x)
    VALUE __setitem__(std::vector< std::string >::difference_type i, std::vector< std::string >::difference_type length, std::vector< std::string,std::allocator< std::string > > const &v)
	from t.rb:4:in `<main>'
```

Regards.

**Comment by tamuratak** [comment]
I confirm this issue still exists for python too.

```sh
$  cat test.i
%module test
%{
#include <memory>
%}
%include <std_vector.i>
%include <std_string.i>
%include <std_shared_ptr.i>
%shared_ptr(std::vector<std::string>)
%template(StringVector) std::vector<std::string>;

$ swig -python -c++ test.i

$ clang++ -I /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/ -I/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -bundle -o _test.so test_wrap.cxx -L /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/ -lpython2.7

$ cat t.py 
import test
str = test.StringVector()
str.append('foo')
str[0] = "bar"

$ /opt/local/bin/python2.7 t.py
Traceback (most recent call last):
  File "t.py", line 4, in <module>
    str[0] = "bar"
  File "/Users/tamura/src/tmp/swig/952/test.py", line 200, in __setitem__
    return _test.StringVector___setitem__(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'StringVector___setitem__'.
  Possible C/C++ prototypes are:
    std::vector< std::string >::__setitem__(PySliceObject *,std::vector< std::string,std::allocator< std::string > > const &)
    std::vector< std::string >::__setitem__(PySliceObject *)
    std::vector< std::string >::__setitem__(std::vector< std::string >::difference_type,std::vector< std::string >::value_type const &)

$ swig -version

SWIG Version 4.0.0

Compiled with g++ [x86_64-apple-darwin16.5.0]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```

**Comment by ojwb** [comment]
It seems this isn't fixed then I guess, so reopening.

@wsfulton Did you test this differently to the most recent comments?

**Comment by carmesean** [comment]
Have there been any updates on the solution to this issue, yet?

**Comment by goatshriek** [comment]
I've determined the cause of this problem, but unfortunately am having some trouble coming up with a solution. The typecheck defined for `std::vector<std::string>` defined in the `std_vector.i` inclusion is being used instead of the override defined by the `%shared_ptr` directive, leading to a broken dispatch function. From the debug output:

    Searching for a suitable 'typecheck' typemap for: std::vector< std::string > *self
      Looking for: std::vector< std::string > *self
      Looking for: std::vector< std::string > *
      Using: %typemap(typecheck) std::vector< std::string,std::allocator< std::string > > *

It seems strange to me that this is matching even though the `std:allocator...` portion is missing, so I would greatly appreciate someone explaining what's happening there to me. This isn't happening for other calls (such as the accessor index operation) because the `const` qualifier appears to be enough to hit the shared_ptr typecheck instead:

    Searching for a suitable 'typecheck' typemap for: std::vector< std::string > const *self
      Looking for: std::vector< std::string > const *self
      Looking for: std::vector< std::string > const *
      Using: %typemap(typecheck) std::vector< std::string > const *

I've tried adding in explicit deletions of the vector typechecks, but so far haven't had any luck with that. The issue can be fixed by adding in a named typecheck for `self` parameters in `shared_ptr`, but that's horrifying. Any recommendations on other ways around this would be welcome.

**Comment by ojwb** [comment]
Still reproduces with the example from tamuratak above.  I used Python3 and Linux with the commands:

```
swig -python -c++ test.i
g++ `python3-config --cflags` test_wrap.cxx -fPIC -shared -o _test.so
python3 t.py
```

Output:

```
Traceback (most recent call last):
  File "/home/olly/git/swig/gh952/t.py", line 4, in <module>
    str[0] = "bar"
  File "/home/olly/git/swig/gh952/test.py", line 160, in __setitem__
    return _test.StringVector___setitem__(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'StringVector___setitem__'.
  Possible C/C++ prototypes are:
    std::vector< std::string >::__setitem__(PySliceObject *,std::vector< std::string,std::allocator< std::string > > const &)
    std::vector< std::string >::__setitem__(PySliceObject *)
    std::vector< std::string >::__setitem__(std::vector< std::string >::difference_type,std::vector< std::string >::value_type const &)

```

**Comment by ojwb** [comment]
Seems to be specific to shared_ptr so tagging as C++11.

Still reproducible for both Python and Ruby with current git.
